// Dossiê VTSD — conteúdo (partes 0 a 5)
const H = require("./gen1.js");
const { add, h1, h2, h3, p, li, ol, citacao, caixa, tabela, esp, quebra, legenda } = H;
const { Paragraph, TextRun, AlignmentType, TableOfContents, HeadingLevel, BorderStyle } = H;

// ============================== CAPA ==============================
add(
  esp(4),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
    children: [new TextRun({ text: "DOSSIÊ DE CONTEÚDO PARA PODCAST", bold: true, size: 24, font: "Calibri", color: H.DOURADO, characterSpacing: 60 })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 100 },
    children: [new TextRun({ text: "Venda Todo Santo Dia", bold: true, size: 72, font: "Calibri", color: H.AZUL })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 300 },
    children: [new TextRun({ text: "O método completo de tráfego pago e criativos", size: 32, font: "Calibri", color: H.AZUL_CLARO })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 480 },
    border: { top: { style: BorderStyle.SINGLE, size: 8, color: H.DOURADO, space: 10 } },
    children: [new TextRun({ text: "" })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 140 },
    children: [new TextRun({ text: "Método de Leandro Ladeira, destilado das apostilas, mapas mentais", size: 22, font: "Calibri", color: H.CINZA })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 140 },
    children: [new TextRun({ text: "e das 150 aulas do curso, mais os aprendizados de aplicação real", size: 22, font: "Calibri", color: H.CINZA })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 600 },
    children: [new TextRun({ text: "em páginas, criativos e campanhas do Studio Delli", size: 22, font: "Calibri", color: H.CINZA })],
  }),
  esp(6),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Documento de trabalho interno · Studio Delli", size: 20, font: "Calibri", color: H.CINZA })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Compilado em 17 de agosto de 2026", size: 20, font: "Calibri", color: H.CINZA })],
  }),
  quebra(),
);

// ============================== COMO USAR ==============================
add(
  h1("Como usar este dossiê"),
  p("Este documento reúne, em um só lugar, todo o método de marketing e tráfego pago do curso **Venda Todo Santo Dia**, de Leandro Ladeira, na forma em que ele foi destilado para uso prático: oito skills de trabalho, o índice completo das 150 aulas, o mapa mental de anúncios e o passo a passo operacional de subir campanha no Meta Ads."),
  p("Ele não foi escrito como resumo. Foi escrito como **matéria-prima de fala** — cada capítulo traz o conceito, o porquê, o exemplo aplicado, o erro comum e o checklist. É material para você abrir no microfone e ir puxando o fio."),
  h2("Três camadas de leitura"),
  add_tabela_camadas(),
  h2("O que está aqui e o que não está"),
  p("**Está aqui:** o método inteiro — produto, copy, página de vendas, VSL, criativos, estratégia de tráfego, execução no Meta Ads, conteúdo orgânico e reaproveitamento de material gravado. Mais os quadros de referência rápida, o glossário, um roteiro sugerido de episódios e as frases prontas para usar no ar."),
  p("**Não está aqui:** o conteúdo literal das aulas em vídeo. Este é o método destilado — a estrutura, os critérios e as decisões — não a transcrição do curso. Onde o material escrito do curso não existia (módulos 2 e 3 não têm apostila), os pontos que dependem da nuance da aula estão marcados com ⚑."),
  caixa("Aviso de uso", [
    "Este dossiê é material interno de estudo e produção de conteúdo. Ele descreve e comenta um método; não redistribui as aulas, as apostilas nem os arquivos do curso.",
    "Ao falar no ar sobre números, resultados ou casos, use apenas o que você pode comprovar. O próprio método é explícito nisso: **nenhuma promessa sem lastro real** — é uma das poucas regras duras que atravessam todas as skills.",
  ]),
  quebra(),
);

function add_tabela_camadas() {
  return tabela(
    ["Camada", "Onde está", "Para que serve no podcast"],
    [
      ["**Conceito**", "Partes 1 a 6", "O bloco de explicação: o que é, por que funciona, de onde vem"],
      ["**Prática**", "Partes 7 e 8", "O bloco de execução: o que fazer na segunda-feira de manhã"],
      ["**Suporte**", "Partes 9 a 14", "Cheat sheets, mapa de interligações, roteiro de episódios, frases, glossário"],
    ],
    [1700, 2100, 5220],
  );
}

// ============================== SUMÁRIO ==============================
add(
  h1("Sumário"),
  p("Atualize o sumário no Word com **F9** (ou clique com o botão direito e escolha Atualizar campo) para gerar os números de página."),
  new TableOfContents("Sumário", { hyperlink: true, headingStyleRange: "1-2" }),
  quebra(),
);

// ============================== PARTE 0 ==============================
add(
  h1("Parte 0 — O mapa: onde o método mora"),
  p("Antes de entrar no conteúdo, vale enxergar o tamanho da coisa. O Venda Todo Santo Dia tem **11 módulos e 150 aulas**. Ele não é um curso de tráfego pago; é um curso de **negócio digital perpétuo**, em que tráfego é um dos módulos. Essa distinção importa para o podcast, porque explica por que quase todo problema de tráfego que as pessoas trazem não é um problema de tráfego."),
  h2("Os 11 módulos"),
  tabela(
    ["#", "Módulo", "Aulas", "Material escrito"],
    [
      ["1", "Introdução", "11", "Apostilas e planilhas"],
      ["2", "Concepção de Produto", "12", "Só vídeo ⚑"],
      ["3", "Criação do Produto na Prática", "10", "Só vídeo ⚑"],
      ["4", "Fluxos de Venda", "22", "—"],
      ["5", "**Copywriting**", "19", "**Completo**: apostilas, mapas mentais, 30 páginas de vendas e 33 anúncios de referência"],
      ["6", "Tráfego Pago com IA", "8", "Skills oficiais de operação do Meta Ads"],
      ["7", "Tráfego Pago", "29", "—"],
      ["8", "Conteúdo", "18", "—"],
      ["9", "O Mercado Digital", "6", "—"],
      ["10", "Administrativo e Financeiro", "8", "—"],
      ["11", "Ferramentas", "7", "—"],
    ],
    [500, 3200, 800, 4520],
  ),
  legenda("A concentração de material escrito está nos módulos 1 e 5. Os módulos 2 e 3 (produto) não têm apostila — os pontos marcados ⚑ neste dossiê dependem da nuance da aula em vídeo."),
  h2("O que cada módulo entrega, em uma frase"),
  li("**1. Introdução** — os 8 erros do perpétuo, a Teoria da Escala, CAC e CPA, projeção financeira. É o módulo que define o vocabulário."),
  li("**2. Concepção de Produto** — situação, posicionamento, identidade do consumidor e do comunicador, QFD, mecanismo único, urgências ocultas, perpétuo x lançamento."),
  li("**3. Criação na Prática** — como criar cada formato: curso, mentoria, ebook, comunidade, desafio, imersão, SaaS, curso certificado."),
  li("**4. Fluxos de Venda** — 22 aulas de arquitetura de funil: conversão direta, remarketing, pré-checkout, mandala, quiz, WhatsApp, isca digital, webinário, pico, upsell, downsell, orderbump, assinatura, high ticket."),
  li("**5. Copywriting** — fundamentos, anúncios, página de vendas, VSL, quebra de objeções, SPIN Selling, mensageria, e os pitches (ticket alto, eventos online, ativação, imersão)."),
  li("**6. Tráfego Pago com IA** — o que mudou no Meta Ads com IA, e as skills de conexão e criação de campanha operadas por agente."),
  li("**7. Tráfego Pago** — 29 aulas: Business Manager, pixel, conversões personalizadas, públicos, motor Andromeda, Advantage+, as campanhas do perpétuo (distribuição, conversão, remarketing), rituais de otimização, e todo o Google Ads."),
  li("**8. Conteúdo** — Instagram (fundamentos, linha editorial, Stories), Lives, os 7 formatos de Reels, e YouTube (fundamentos, SEO, recomendados, linha editorial)."),
  li("**9. O Mercado Digital** — a lógica do mercado, como ser bom expert, como ser bom lançador, como encontrar cada um."),
  li("**10. Administrativo e Financeiro** — tipos de empresa, PF x PJ, nota fiscal, organização financeira, reinvestimento, distribuição de lucro."),
  li("**11. Ferramentas** — anatomia de páginas, construtores, e-mail, limpeza de lista, pagamentos, área de membros, suporte, métricas."),
  esp(),
  caixa("Gancho de episódio", [
    "Um curso de 150 aulas sobre vender todo dia dedica **29 aulas** a tráfego pago e **22** a fluxos de venda. Ou seja: quase o mesmo peso para “como levar gente” e “por onde a gente passa”. A maioria das pessoas estuda só a primeira metade — e é por isso que o tráfego delas não converte.",
  ]),
  quebra(),
);

// ============================== PARTE 1 ==============================
add(
  h1("Parte 1 — A ordem que não se inverte"),
  p("Existe uma sequência de trabalho no método, e a maior parte dos fracassos vem de pular uma etapa. A ordem é esta:"),
  esp(),
  tabela(
    ["Etapa", "Pergunta que ela responde", "Se você pular"],
    [
      ["**1. Produto**", "Contra o que eu estou sendo comparado?", "Você escreve uma página boa para um produto mal posicionado. Não vende."],
      ["**2. Copy**", "Por que alguém leria a próxima linha?", "Você produz texto informativo, não persuasivo."],
      ["**3. Página de vendas**", "Onde a decisão acontece?", "Você paga tráfego para uma página que não sustenta a promessa do anúncio."],
      ["**4. VSL**", "O que eu falo em quatro minutos?", "Você abre a página com imagem estática, e perde o ativo que mais converte."],
      ["**5. Criativos**", "Qual o gancho e para quem?", "Você sobe três anúncios iguais e chama de teste."],
      ["**6. Tráfego**", "Que estrutura e que público?", "Você otimiza orçamento quando o problema era a oferta."],
    ],
    [1750, 3200, 4070],
  ),
  esp(),
  h2("O diagnóstico ao contrário"),
  p("Quando algo não está vendendo, o método manda diagnosticar na **ordem inversa da suspeita natural**. A tentação é olhar o orçamento primeiro. O método olha por último."),
  ol("**Oferta** — o que está sendo oferecido resolve algo que a pessoa quer resolver agora?"),
  ol("**Página** — ela sustenta a promessa que o anúncio fez?"),
  ol("**Criativo** — o gancho para o público certo?"),
  ol("**Público** — a segmentação está estrangulando o aprendizado?"),
  ol("**Orçamento** — só agora."),
  esp(),
  citacao("Diagnóstico de “não está vendendo”, em ordem: oferta → página → criativo → público → orçamento. Quase nunca é o último.", "skill trafego-estrategia"),
  h2("Os dois sinais que separam os problemas"),
  p("Há um par de números que resolve a maior discussão de qualquer operação — “é o tráfego ou é a página?”:"),
  li("**Pouco clique** no anúncio (CTR baixo) → problema de **criativo ou público**. Não é orçamento."),
  li("**Muito clique e pouca venda** → problema de **página**. A página não sustenta o que o anúncio prometeu."),
  p("É simples, é operacional, e é o tipo de coisa que rende três minutos muito bons de podcast, porque quase todo ouvinte já viveu os dois casos sem saber diferenciar."),
  quebra(),
);

// ============================== PARTE 2 ==============================
add(
  h1("Parte 2 — Produto: posicionamento e mecanismo único"),
  p("Fonte: módulos 2 e 3 do curso. Estes dois módulos **não têm apostila** — o conteúdo detalhado está nos vídeos. Os conceitos marcados com ⚑ são aqueles em que vale conferir a aula para a nuance exata do Ladeira."),
  h2("Situação antes de posicionamento"),
  p("O curso separa a decisão do produto em dois momentos, e a ordem importa."),
  p("**Situação** é de onde você parte: a autoridade que já tem, a audiência que já tem, o que consegue provar, quanto tempo e quanto dinheiro pode investir. Produto certo para a situação errada não vende."),
  p("**Posicionamento** é o lugar que o produto ocupa na cabeça do comprador. E aqui está a definição que rende conteúdo: posicionamento **não é o que o produto é — é contra o que ele é comparado**."),
  h3("O exemplo aplicado"),
  p("Um curso de DIALux (software de cálculo luminotécnico) posicionado como “curso de software” compete com tutorial gratuito do YouTube. Posicionado como “como entregar projeto luminotécnico profissional, com memorial de cálculo, e cobrar por isso”, ele compete com **continuar fazendo projeto no achismo**."),
  p("Mesmo produto. Mesmo conteúdo. Concorrente diferente — e, portanto, preço diferente."),
  h2("As duas identidades"),
  p("Duas identidades precisam se encontrar para a comunicação funcionar:"),
  li("**Identidade do Consumidor** — quem ele é, do que tem medo, o que quer parecer ser, com quem se compara, que palavras usa."),
  li("**Identidade do Comunicador** — quem você é na comunicação, que tom você sustenta, o que só você pode dizer com legitimidade."),
  p("Quando as duas não conversam, a copy soa falsa mesmo estando tecnicamente correta. É a explicação mais elegante que o método dá para aquele texto que está certo e ainda assim não convence."),
  h2("Urgências ocultas ⚑"),
  p("O que faz alguém comprar **agora**. Três sabores — e eles reaparecem no dossiê inteiro, porque são também os três ganchos de anúncio e a abertura de VSL:"),
  tabela(
    ["Sabor", "Pergunta que o comprador se faz", "Exemplo (iluminação)"],
    [
      ["**Dúvida**", "Qual a diferença entre X e Y?", "Lux ou lúmen, o que eu especifico?"],
      ["**Dor**", "Por que isso está acontecendo comigo?", "Meu projeto foi refeito pelo eletricista"],
      ["**Desejo**", "Como eu chego lá?", "Quero entregar um dossiê que justifique meu honorário"],
    ],
    [1400, 3400, 4220],
  ),
  h2("Mecanismo único — a furadeira ⚑"),
  p("A aula mais longa do módulo de produto (52 minutos) chama-se “Mecanismo único - Furadeira”. A referência é o clássico: ninguém quer a furadeira, quer o furo. Mas o método vai um passo além — o **mecanismo único** é o que explica *por que o seu furo é diferente*."),
  p("Sem mecanismo único, o produto vira commodity e só resta competir por preço."),
  h3("O que faz um mecanismo único ser bom"),
  li("Tem **nome próprio**."),
  li("Explica **por que os outros métodos falham**."),
  li("É **demonstrável**, não apenas afirmado."),
  esp(),
  caixa("O teste do mecanismo", [
    "Se você não consegue mostrar o mecanismo funcionando na tela, ele não é um mecanismo — é uma promessa. E promessa sem demonstração é exatamente o que o público técnico desconta na hora.",
  ]),
  h2("A Teoria do QFD ⚑"),
  p("*Quality Function Deployment*: desdobrar o que o cliente **diz que quer** no que o produto precisa **efetivamente entregar**. Serve para dois propósitos práticos — não construir módulo que ninguém pediu, e achar o entregável que resolve várias demandas ao mesmo tempo."),
  p("Uso prático em três passos: liste o que o público pede em voz alta; traduza cada item no atributo real do produto; priorize os atributos que atendem mais pedidos."),
  h2("Preço e formato são uma decisão só"),
  p("O curso trata precificação e formato como **uma única decisão**: o formato entrega a promessa, e o preço comunica o posicionamento."),
  tabela(
    ["Formato", "Custo de produção", "Ticket típico"],
    [
      ["Ebook, PDF, planilha, template", "Baixo", "Entrada"],
      ["Curso gravado", "Médio", "Entrada / médio"],
      ["Desafio", "Médio", "Entrada / médio"],
      ["Comunidade", "Contínuo", "Recorrência"],
      ["Mentoria", "Alto (seu tempo)", "Alto"],
      ["Evento de imersão ao vivo", "Alto", "Alto"],
      ["SaaS", "Muito alto", "Recorrência"],
      ["Curso certificado (MEC, pós, MBA)", "Alto + burocracia", "Alto"],
    ],
    [4020, 2600, 2400],
  ),
  esp(),
  p("E daí sai uma regra de coerência que atravessa a página de vendas e o VSL: **ticket baixo → preço exposto; ticket alto → preço omitido**, levando para conversa."),
  h2("Perpétuo x lançamento: produtos diferentes"),
  p("Este é um dos pontos mais mal entendidos do mercado, e o método é categórico: perpétuo e lançamento **não são o mesmo produto em calendários diferentes**. São produtos diferentes."),
  li("**Perpétuo** vende todo dia, com fluxo sempre ligado. Precisa de oferta que se sustenta **sem data**."),
  li("**Lançamento** concentra venda em janela, e pode depender de escassez real."),
  p("A consequência prática é dura e aparece de novo na Parte 4: em perpétuo, **não se constrói a oferta em cima de escassez artificial**. Constrói-se em cima de argumento permanente."),
  h2("Escada de produtos sem canibalização"),
  p("Ao adicionar um produto novo, três perguntas:"),
  ol("Ele atende **outro momento** do mesmo cliente, ou o mesmo momento?"),
  ol("Se o cliente comprar o novo, ele deixa de precisar do antigo? (canibalização)"),
  ol("A escada sobe em **profundidade de transformação**, ou só em preço?"),
  quebra(),
);

// ============================== PARTE 3 ==============================
add(
  h1("Parte 3 — Copywriting: os fundamentos"),
  p("Fonte: módulo 5, aula 1 (54 minutos, com apostila e mapa mental). Vale para qualquer peça — e-mail, anúncio, legenda, roteiro, proposta comercial — não apenas para página de vendas."),
  citacao("Copy é a arte de transformar letras em número.", "Venda Todo Santo Dia"),
  h2("O básico que ninguém fala"),
  p("Antes de gatilho e de fórmula, três coisas sustentam qualquer texto. É o trecho do método que mais destoa do que se vê por aí — e o melhor bloco de abertura para um episódio sobre copy."),
  h3("Coesão"),
  p("A cola entre as partes: palavras de ligação, encadeamento certo dos argumentos, estrutura que guia o leitor sem que ele se perca. Sem coesão o texto vira colcha de retalhos — desconectado, confuso, cansativo."),
  h3("Coerência"),
  p("A lógica interna: tudo o que é dito conversa com o propósito central. Não adianta começar falando de produtividade e no meio entrar em alimentação. Texto coerente respeita o que promete, não se contradiz e não foge do tema."),
  h3("Simplicidade"),
  p("**Não é mediocridade, é maturidade.** Quem domina o assunto explica fácil. Quem complica geralmente não entendeu o próprio pensamento. É a ponte entre a sua ideia e o entendimento do outro."),
  esp(),
  caixa("A frase que fecha o bloco", [
    "Um texto sem esses três não é salvo por gatilho nenhum.",
  ]),
  h2("Os 3 elementos da persuasão"),
  p("Toda peça persuasiva precisa dos três, e a ausência de qualquer um deles tem um sintoma reconhecível."),
  tabela(
    ["Elemento", "Matéria-prima", "Sintoma quando falta"],
    [
      ["**Lógica**", "Argumentos, números, dados", "A pessoa se empolga e não compra"],
      ["**Emoção**", "Histórias, desejos, medos", "A pessoa entende e não se move"],
      ["**Credibilidade**", "Autoridade, provas, garantias", "A pessoa quer e não confia"],
    ],
    [1900, 3300, 3820],
  ),
  esp(),
  p("A base teórica é Kahneman: **as pessoas tomam decisões com emoção e justificam com lógica**. Os dois motores são **medo** e **ganância**."),
  p("A consequência prática é uma frase que cabe inteira num corte de podcast: a emoção abre a porta, a lógica dá permissão para comprar. Peça só de lógica não move; peça só de emoção não fecha."),
  citacao("O cérebro odeia pensar. Ele prefere decidir sentindo.", "Venda Todo Santo Dia"),
  h2("A régua de Blair Warren"),
  p("As pessoas farão qualquer coisa por aqueles que:"),
  ol("as **encorajam a sonhar**"),
  ol("as ajudam a **justificar seus fracassos**"),
  ol("as **tranquilizam contra seus medos**"),
  ol("**confirmam suas suspeitas**"),
  ol("e as ajudam a **atacar seus inimigos**"),
  esp(),
  p("Use como filtro de revisão: se o texto não faz nenhuma das cinco, ele é informativo, não persuasivo."),
  h3("As duas que mais rendem na prática"),
  li("**Confirmar a suspeita** — “você sempre desconfiou que [prática comum do mercado] é chute”. O leitor já pensava isso; você dá nome e razão. É a mais poderosa com público técnico, porque valida a inteligência dele."),
  li("**Justificar o fracasso** — “não é falta de talento nem de inteligência; ninguém te ensinou [a ponte que falta]”. Tira a culpa do leitor **sem tirar a responsabilidade**."),
  h3("O cuidado com “atacar o inimigo”"),
  p("Exige um inimigo bem escolhido: **nunca uma pessoa ou empresa, sempre uma prática** — o achismo, o improviso, a dependência de terceiro. É a diferença entre construir uma tese e entrar numa briga."),
  h2("Os 26 gatilhos mentais"),
  p("São atalhos que o cérebro usa para decidir rápido. Previsíveis, inconscientes e acionáveis — funcionam porque o cérebro busca eficiência, não perfeição."),
  tabela(
    ["", "", ""],
    [
      ["Escassez", "Urgência", "Prova social"],
      ["Autoridade", "Reciprocidade", "Compromisso e coerência"],
      ["Afinidade", "Antecipação", "Novidade"],
      ["História", "Curiosidade", "Comunidade / pertencimento"],
      ["Polarização / inimigo comum", "Segurança / garantia", "Exclusividade"],
      ["Simplicidade / clareza", "Dor vs prazer", "Transformação"],
      ["Autorreflexão (espelho)", "Status", "Consistência"],
      ["Validação externa", "Autoridade moral / causa nobre", "Contraste (antes e depois)"],
      ["Prova lógica", "Ambiguidade zero", ""],
    ],
    [3006, 3006, 3008],
  ),
  esp(),
  p("**Como usar:** escolha 3 a 5 que sustentem o argumento central e construa em cima deles. Gatilho não é tempero polvilhado no fim — **é estrutura**."),
  caixa("Onde quase todo mundo erra", [
    "Escassez e urgência só funcionam quando são **reais**. Em produto de perpétuo, escassez inventada destrói confiança — e mais rápido ainda com público técnico, que reconhece o truque na hora.",
  ]),
  h2("O filtro de público"),
  p("Estabeleça **para quem é** logo na primeira linha. Quem não é do público para de ler — e isso é bom, porque a peça não foi feita para ele. Quem é, se identifica e fica."),
  citacao("Se você é arquiteto e ainda entrega projeto de iluminação sem cálculo…"),
  p("Em anúncio pago, isso tem consequência financeira direta: você deixa de pagar por visualização irrelevante. É o mesmo mecanismo que, em conteúdo orgânico, melhora a retenção."),
  h2("O processo de revisão em 7 passos"),
  p("Passe qualquer texto por esta ordem:"),
  ol("**Coerência** — tudo conversa com o propósito central? Alguma parte foge?"),
  ol("**Coesão** — as frases se conectam ou são blocos soltos?"),
  ol("**Simplicidade** — dá para dizer o mesmo com menos? Alguma frase precisa ser relida?"),
  ol("**Blair Warren** — faz alguma das cinco coisas?"),
  ol("**Três elementos** — tem lógica, emoção e credibilidade?"),
  ol("**Filtro de público** — dá para saber para quem é nas primeiras linhas?"),
  ol("**Lastro** — toda afirmação tem base real? Nenhum número inventado?"),
  esp(),
  p("A entrega da revisão tem formato: **o que está fraco → por quê → reescrita sugerida**."),
  h2("A regra dura"),
  citacao("Nunca invente número, depoimento, resultado ou prova. Copy boa não precisa disso, e copy que precisa disso não sobrevive ao primeiro cliente cético.", "skill copywriting"),
  quebra(),
);

// ============================== PARTE 4 ==============================
add(
  h1("Parte 4 — Página de vendas: as 16 seções e o resto"),
  p("Fonte: módulo 5, aulas de Página de Vendas e Exemplo de Páginas que Faturam Alto — o trecho do curso com mais material escrito: apostila, mapa mental, 30 prints de páginas reais e 7 páginas completas em PDF. Somado a isso, este capítulo carrega os aprendizados de construir páginas de verdade, marcados com ⚑."),
  h2("O objetivo da página, em ordem"),
  ol("**Não é vender — é apresentar o produto.**"),
  ol("**Fazer a pessoa ler a próxima linha.** Cada linha vende a linha seguinte."),
  ol("Despertar interesse, educar, gerar desejo."),
  ol("Vender."),
  esp(),
  p("O critério que sai disso é implacável: se uma seção não empurra o leitor para a seguinte, ela está sobrando. Corte."),
  h2("A anatomia de toda seção"),
  tabela(
    ["Parte", "Função"],
    [
      ["**Headline**", "Promete o que a seção entrega"],
      ["**Subheadline**", "Qualifica, contextualiza ou adiciona tensão"],
      ["**Conteúdo**", "Entrega o que a headline prometeu"],
    ],
    [2400, 6620],
  ),
  h3("Os 4 erros de headline"),
  ol("**Headline desconexa** do conteúdo da seção."),
  ol("**Headline sem copy** — o mais comum: joga “Depoimentos” e larga os prints sem texto que enquadre o que o leitor deve concluir."),
  ol("**Mais de um conteúdo na mesma seção** — uma seção, uma ideia."),
  ol("**Seção sem headline** — o leitor entra sem saber o que está olhando."),
  h2("⚑ Densidade e ritmo: página não é documento"),
  p("Este é o aprendizado mais transferível de todos, e o mais fácil de contar no ar: **o erro número um ao gerar página com IA é produzir um documento em vez de uma página**. Página de vendas é escaneada, não lida."),
  p("Daí os limites duros:"),
  tabela(
    ["Elemento", "Máximo"],
    [
      ["Headline", "12 palavras"],
      ["Subheadline", "25 palavras"],
      ["Corpo de seção", "60 palavras — passou disso, vira lista"],
      ["Parágrafo", "3 linhas, e nunca dois longos seguidos"],
      ["Item de lista", "15 palavras"],
      ["Exceções", "Seção do autor (150) e respostas de FAQ (50 cada)"],
    ],
    [2600, 6420],
  ),
  esp(),
  h3("A escala de preferência"),
  p("Sempre que houver escolha: lista com ícone **>** parágrafo · card **>** texto corrido · tabela **>** descrição · número grande com legenda **>** explicação · imagem com legenda de uma linha **>** descrever a imagem."),
  h3("Ritmo"),
  p("Nenhuma tela de rolagem pode conter só texto. Todo bloco de texto vem acompanhado de um elemento visual — imagem, card, ícone, número, divisor ou CTA."),
  h3("Peso das seções"),
  p("Sem hierarquia de peso, o gerador trata todas as seções igual e infla a página:"),
  li("**Pesadas** (podem ocupar tela cheia): demonstração visual, currículo, oferta."),
  li("**Médias** (meia tela, sempre com visual): dor, resultados, para quem é, comparação, autor, prova, FAQ."),
  li("**Leves** (2 a 4 linhas no total): quebra de mito, nível, bônus, garantia, ancoragem, clientes."),
  h3("CTA a cada duas seções"),
  p("**8 ou mais chamadas ao longo da página, não 3.** É o padrão que se repete em todas as páginas de alto faturamento analisadas. Além dos CTAs completos (hero, oferta, final), entram faixas curtas de uma linha mais botão depois das seções fortes, e barra fixa no mobile a partir do momento em que o hero sai da tela."),
  caixa("O teste de dez segundos", [
    "Percorra a página imaginando um celular. **Duas telas de rolagem sem botão visível = acrescente um.**",
  ]),
  h2("As 16 seções disponíveis"),
  p("Escolha as que o produto pede, na ordem que faz o argumento avançar."),
  tabela(
    ["#", "Seção", "Observação"],
    [
      ["1", "Cabeçalho", ""],
      ["2", "**Chamada pra ação**", "Ver a regra de preço abaixo"],
      ["3", "**Demonstração**", "Mostrar o produto funcionando — seção pesada"],
      ["4", "**Pra quem é** (e pra quem não é)", "O filtro de público, em seção"],
      ["5", "Explicação do produto", ""],
      ["6", "**Explicação da oferta**", "Entregáveis; entregável forte ganha seção própria"],
      ["7", "Garantia", ""],
      ["8", "**Prova**", "Ver a Parte 4.5 quando não existe prova social"],
      ["9", "Autoridade", ""],
      ["10", "Objeções", ""],
      ["11", "Perguntas frequentes", "Respostas até 50 palavras"],
      ["12", "**Suporte**", "A mais esquecida. Todas as páginas de alto faturamento têm “fale comigo antes de comprar”"],
      ["13", "Argumentos", "Estudos, notícias, lógica, pesquisas"],
      ["14", "Dores e desejos", ""],
      ["15", "Autor", "Até 150 palavras"],
      ["16", "Comparação", ""],
    ],
    [500, 3000, 5520],
  ),
  esp(),
  h3("A regra de preço"),
  li("**Preço barato → mostre o preço.** É argumento de conversão."),
  li("**Preço alto → omita.** Leve para conversa; o preço vem depois do valor."),
  h2("⚑ Perpétuo não usa escassez"),
  p("Em perpétuo: **nada de contador regressivo, vaga limitada ou “últimas horas”**. Escassez falsa destrói confiança — e mais rápido ainda com público técnico (engenheiro, arquiteto, médico, advogado), que reconhece o truque na hora."),
  citacao("A ausência de contador não é omissão. É acerto."),
  h2("⚑ Bônus por benefício, não por stack monetário"),
  p("O reflexo do mercado é montar “Bônus 1: R$ 497 + Bônus 2: R$ 397 = R$ 2.891 de valor, você paga R$ 297”. Isso quebra em dois casos, e os dois são comuns:"),
  ol("**Os valores são inventados.** Se você não vende aquele bônus separado por aquele preço, o número é ficção — dentro de uma página que depende de ser verdadeira."),
  ol("**Público cético reconhece.** Profissional formado desconta o número inflado e passa a duvidar do resto."),
  esp(),
  p("O que funciona melhor: dar a cada bônus o **benefício** que ele entrega, com um selo curto. Exemplo real, de curso técnico:"),
  tabela(
    ["Selo", "Bônus", "Argumento"],
    [
      ["TEMPO", "Assistente de IA", "Não perde tempo caçando informação nem quebrando a cabeça"],
      ["SEGURANÇA", "Projeto modelado pronto", "Quando algo não bater, abre o modelo e compara"],
      ["CAMINHO", "Modelo de relatório", "Parte de um formato que funciona em vez de inventar"],
      ["PRECISÃO", "Planilha / arquivo de cálculo", "Resolve o que o software principal não faz"],
      ["BIBLIOTECA", "Catálogo de fornecedores", "Não trava no meio do projeto procurando insumo"],
    ],
    [1500, 2700, 4820],
  ),
  esp(),
  p("E fecha com a tese, que é uma frase de podcast pronta: **“o produto vale dinheiro; os bônus valem tempo”**."),
  h3("Onde vai o trabalho monetário"),
  p("Na **ancoragem de valor**, em seção separada, onde o número é real: quanto o mercado paga pelo serviço que o comprador vai passar a prestar."),
  p("⚑ E a ancoragem precisa ser **exatamente** o que o produto entrega. Se o curso ensina a validar projeto no software, ancore em *consultoria de validação*, não em *projeto completo* — que envolve visita de obra e compatibilização que o curso não cobre. Ancoragem imprecisa confunde e derruba credibilidade."),
  h2("⚑ Prova quando não existe prova social"),
  p("Produto novo não tem aluno, logo não tem depoimento. **Não invente. Não deixe vazio.** Ordem de preferência:"),
  ol("**Depoimento em vídeo** de quem já usou, mesmo informalmente. Só nome e cargo embaixo — sem texto escrito, sem aspas, sem estrelinhas."),
  ol("**Prova de trabalho**: os projetos e entregas reais de quem ensina. A copy precisa deixar explícito que é competência do instrutor, não resultado de aluno."),
  ol("**Clientes e parceiros**: faixa de logos. Confirme autorização de uso de marca; sem ela, troque por texto genérico (“projetos entregues para incorporadoras e redes de varejo”)."),
  ol("**Beta pago**: libere para 10 a 15 pessoas com desconto, colha depoimento real, e só então escale tráfego."),
  h3("O roteiro de depoimento"),
  p("Depoimento solto sai elogioso e vazio. Mande para quem vai gravar um pedido de 60 a 90 segundos respondendo três perguntas:"),
  ol("**Como você fazia isso antes?**"),
  ol("O que mudou depois?"),
  ol("Para quem você recomendaria?"),
  esp(),
  caixa("O detalhe que vale o episódio", [
    "**O item 1 é o que converte.** Quando a pessoa descreve o problema que tinha, o espectador se reconhece. Elogio ao professor não vende; descrição da dor anterior vende.",
  ]),
  h2("⚑ Apresentação de imagem"),
  p("Print cru de software parece amador. **Emoldure como janela de aplicativo**: container com borda clara, cantos arredondados, sombra suave e uma barra superior cinza com três círculos e uma legenda nomeando a etapa. O mesmo print vira peça de interface."),
  p("Se o material é aula gravada, **manter a webcam do instrutor no canto é bom** — prova que é aula real, não peça de marketing."),
  p("Para sequência de progresso (antes → depois), numere as etapas. Numeração só se presta quando a ordem carrega informação real; nunca como enfeite."),
  h2("⚑ Identidade visual quando o produto ensina ferramenta de terceiro"),
  p("É tentador clonar a identidade visual da ferramenta. Três riscos antes:"),
  ol("**Se a ferramenta é gratuita**, herdar a cara dela sugere ao visitante que o conteúdo também deveria ser."),
  ol("**Conflito de posicionamento**: se a página diz “não é curso de software, é competência”, vestir a marca do software comunica o oposto."),
  ol("**Confusão de marca**: paleta e tipografia semelhantes podem sugerir chancela que não existe."),
  esp(),
  p("**Nunca crie um logo imitando marca registrada de terceiro.** Crie a identidade do *seu* produto, cite a ferramenta nominalmente (uso legítimo) e use capturas de tela — a familiaridade vem daí, de forma autêntica."),
  p("Sobre botões: reserve **uma** cor exclusivamente para compra. Botões secundários (WhatsApp, suporte) usam estilo outline — se ficarem iguais ao de compra, canibalizam o CTA."),
  h2("⚑ Se for gerar a página em ferramenta de IA"),
  p("**Escreva a copy inteira antes e passe pronta.** Dar liberdade de redação a um gerador produz documento, não página de vendas. No prompt, inclua explicitamente:"),
  li("“use EXATAMENTE o texto fornecido, não reescreva, não expanda”"),
  li("os limites de palavras da tabela de densidade"),
  li("a contagem de CTAs esperada"),
  li("o peso de cada seção"),
  li("a paleta em hex e a cor de ação isolada"),
  li("“não invente depoimento, número de alunos, selo ou seção que não pedi”"),
  esp(),
  p("E junte os ajustes numa mensagem só — cada ida e volta com o agente consome crédito."),
  h2("Checklist final da página"),
  li("Cada seção tem headline, subheadline e conteúdo"),
  li("Nenhuma headline desconexa do próprio conteúdo"),
  li("Nenhuma seção com duas ideias"),
  li("Nenhuma imagem ou depoimento sem copy enquadrando"),
  li("Limites de palavras respeitados; nenhum bloco parece texto de blog"),
  li("8 ou mais CTAs e barra fixa no mobile"),
  li("Lógica, emoção e credibilidade presentes — e não competindo no mesmo bloco"),
  li("Objeções principais respondidas antes do CTA final"),
  li("Preço exposto (ticket baixo) ou omitido (ticket alto)"),
  li("Garantia clara"),
  li("Seção de suporte presente"),
  li("Ancoragem de valor corresponde exatamente ao que o produto entrega"),
  li("Sem escassez falsa se o produto é perpétuo"),
  li("Zero invenção: nenhum número, depoimento, selo ou logo sem lastro"),
  li("A página inteira sustenta **um** argumento central"),
  quebra(),
);

// ============================== PARTE 5 ==============================
add(
  h1("Parte 5 — VSL: o vídeo de vendas"),
  p("Fonte: módulo 5, aula de VSL — **52 minutos, a mais longa do módulo de copy**. E as páginas de alto faturamento analisadas **abrem com vídeo, não com imagem estática**. Os dois fatos juntos dizem o mesmo: VSL é peça central, não acessório."),
  h2("Três definições antes de roteirizar"),
  ol("**Temperatura do público.** Tráfego frio (anúncio) precisa de mais aquecimento; tráfego de canal próprio já chega aquecido. Um VSL bem-feito serve aos dois: quem já conhece pula para o preço, quem não conhece aquece ali mesmo."),
  ol("**Ticket.** Ticket baixo aguenta conversão direta — fale o preço no vídeo. Ticket alto pede conversa; o vídeo leva para agendamento, não para checkout."),
  ol("**O argumento central.** O mesmo da página. O vídeo não pode defender outra tese."),
  h2("A estrutura de 4 minutos (venda direta, ticket baixo)"),
  tabela(
    ["Tempo", "Bloco", "O que faz"],
    [
      ["0:00–0:15", "**Gancho + filtro**", "Urgência oculta (dúvida, dor ou desejo) e “para quem é” na primeira frase"],
      ["0:15–0:45", "**Confirma a suspeita**", "O leitor já desconfiava; você dá nome ao problema"],
      ["0:45–1:15", "**Justifica o fracasso**", "“Não é falta de talento” + conte que você também travou"],
      ["1:15–2:15", "**Demonstração**", "Mostre a coisa funcionando. É o trecho que mais vende"],
      ["2:15–2:45", "**Inimigo comum**", "A prática que você combate — nunca uma pessoa"],
      ["2:45–3:30", "**Oferta**", "O que vem junto, o preço, a comparação de valor"],
      ["3:30–4:00", "**Garantia e CTA**", "Assuma o risco e diga exatamente o que fazer"],
    ],
    [1200, 2200, 5620],
  ),
  esp(),
  p("Note a arquitetura: os blocos 2 e 3 são **Blair Warren aplicado em sequência** (confirmar a suspeita, justificar o fracasso), e o bloco 4 é o **mecanismo único sendo demonstrado**. O VSL é o método inteiro em quatro minutos."),
  h2("Regras de execução"),
  li("**Fale o preço em voz alta** em ticket baixo. Esconder cria atrito sem ganho."),
  li("**Compartilhe a tela na demonstração** e ocupe o quadro inteiro. Prova visual vale mais que qualquer adjetivo."),
  li("**Primeiros 15 segundos sem introdução.** Nada de “olá, seja bem-vindo, hoje eu vou falar”. Comece pelo gancho."),
  li("**Um CTA, repetido.** Não ofereça dois caminhos."),
  li("Produção importa menos que clareza: **áudio limpo > câmera cara**."),
  h2("A estrutura longa (webinário / ticket alto)"),
  p("Mesma espinha, com dois blocos adicionais antes da oferta:"),
  li("**Conteúdo de valor real** — ensine algo aplicável antes de vender. É o que compra o direito de fazer a oferta."),
  li("**Quebra de objeções uma a uma** — cada objeção vira um bloco curto, com a resposta e, se possível, uma prova."),
  h2("O detalhe de engenharia que economiza retrabalho"),
  p("Deixe o campo do vídeo pronto **antes de gravar**. O padrão que funciona:"),
  li("Uma constante (`VSL_VIDEO_ID`) no topo do componente"),
  li("Vazia: mostra a imagem principal"),
  li("Preenchida: troca pelo player **no mesmo espaço e proporção**, sem quebrar o layout"),
  li("O player mantém a mesma moldura visual da imagem que substituiu"),
  esp(),
  p("Assim a página pode ir ao ar antes de o vídeo existir, e o vídeo entra sem retrabalho. É pequeno, mas é o tipo de decisão que separa quem publica de quem fica esperando o vídeo ficar pronto."),
  h2("Checklist do roteiro"),
  li("Gancho nos primeiros 15 segundos, sem introdução"),
  li("Público filtrado na primeira frase"),
  li("Confirma uma suspeita real do espectador"),
  li("Justifica o fracasso dele sem tirar a responsabilidade"),
  li("Tem demonstração visual, não só fala"),
  li("O inimigo é uma prática, não uma pessoa ou empresa"),
  li("Lógica, emoção e credibilidade aparecem"),
  li("Preço dito em voz alta (ticket baixo)"),
  li("Garantia declarada"),
  li("Um único CTA, repetido"),
  li("Nenhuma promessa sem lastro"),
  quebra(),
);

module.exports = H;
