// Dossiê VTSD — conteúdo (partes 6 a 8): criativos, estratégia e execução
const H = require("./gen2.js");
const { add, h1, h2, h3, p, li, ol, citacao, caixa, tabela, esp, quebra, legenda } = H;

// ============================== PARTE 6 — CRIATIVOS ==============================
add(
  h1("Parte 6 — Criativos: as 4 anatomias e as 18 limitações"),
  p("Fonte: módulo 5, aula 02 (Anúncios) — 37 minutos, com apostila, mapa mental e **33 anúncios de referência** separados entre descoberta e relacionamento. Este é o coração do material de criativo, e provavelmente o capítulo mais aproveitável do dossiê para conteúdo, porque resolve a pergunta que todo mundo faz: “o que eu gravo?”."),
  h2("A estrutura comum a todo anúncio"),
  esp(),
  new H.Paragraph({
    alignment: H.AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [new H.TextRun({ text: "Gancho  →  Desenvolvimento  →  CTA", bold: true, size: 28, font: "Consolas", color: H.AZUL })],
  }),
  p("Sempre esses três. O que muda de uma anatomia para outra é **o gancho, o CTA, o público e o objetivo de campanha**. O corpo do anúncio — o desenvolvimento — obedece sempre à mesma regra: entregar o que o gancho prometeu."),
  h2("O gancho tem dois tipos"),
  h3("Indireto"),
  p("Não fala objetivamente do produto nem do problema. Entra por analogia, história ou curiosidade. Os exemplos do mapa mental do curso são deliciosamente aleatórios de propósito: **cinema, mercado, Albert Einstein**."),
  p("É melhor para topo de funil, onde o leitor ainda não sabe que tem o problema. Se ele não sabe que tem o problema, um gancho direto sobre o problema não o alcança."),
  h3("Direto"),
  p("Ataca uma **urgência oculta** — os mesmos três sabores que apareceram na concepção do produto e na abertura do VSL:"),
  tabela(
    ["Sabor", "Formato", "Exemplo do curso", "Exemplo aplicado"],
    [
      ["**Dúvida**", "“Qual a diferença entre X e Y”", "Qual a diferença entre perpétuo e lançamento", "Qual a diferença entre lux e lúmen no projeto"],
      ["**Dor**", "“Por que [seu problema] acontece”", "Por que seu produto não está vendendo", "Por que seu projeto de iluminação é reprovado pelo cliente"],
      ["**Desejo**", "“Como [resultado desejado]”", "Como aumentar sua taxa de conversão", "Como entregar memorial de cálculo em 1 dia"],
    ],
    [1200, 2300, 2760, 2760],
  ),
  h2("O filtro de copy"),
  p("Estabelecer **o público logo no primeiro momento** — a primeira linha já diz para quem é. Quem não é do público para de assistir (e isso é bom: você não paga por visualização irrelevante); quem é, fica."),
  p("No mapa mental do curso esse ponto tem até um apelido de exemplo — “exemplo Claudinha” — que é a personificação do público que você quer filtrar para dentro."),
  h2("As 4 anatomias"),
  p("Cada anatomia é uma combinação fixa de gancho, CTA, público e objetivo. Não são estilos; são **funções dentro do funil**."),
  h3("Anatomia 1 — Descoberta"),
  p("Topo de funil. Alcançar quem ainda não te conhece."),
  li("**Gancho:** indireto ou direto com urgência oculta"),
  li("**CTA:** Siga · Comente · Compartilhe"),
  li("**Público:** + interesses, lookalike, aberto · – seguidores e listas quentes/mornas · – clientes"),
  li("**Objetivo de campanha:** Get Views (50% ou 90%) ou Seguidores"),
  h3("Anatomia 2 — Relacionamento"),
  p("Aquecer quem já te conhece."),
  li("**Gancho:** indireto ou direto com urgência oculta"),
  li("**CTA:** Comente · Compartilhe"),
  li("**Público:** + seguidores e listas quentes/mornas · – clientes"),
  li("**Objetivo:** Get Views (50% ou 90%)"),
  h3("Anatomia 3 — Conversão"),
  p("Levar para a página, ou capturar o lead."),
  li("**Gancho:** direto com urgência oculta (dúvidas, dores, desejos) — aqui o indireto sai de cena"),
  li("**CTA:** Saiba mais · Entenda · Aula gratuita"),
  li("**Público:** + interesses, lookalike, aberto + seguidores e listas quentes/mornas · – clientes"),
  li("**Objetivo:** Conversão (lead ou venda)"),
  h3("Anatomia 4 — Remarketing"),
  p("Fechar quem já demonstrou intenção. Tem um componente que nenhuma outra tem: **prontidão**."),
  li("**Gancho:** indireto ou direto + urgência oculta + **prontidão** — o leitor já sabe do que se trata; fale como quem retoma a conversa, não como quem se apresenta"),
  li("**CTA:** Compre · Garanta"),
  li("**Público:** + quem entrou na página de vendas · – clientes"),
  li("**Objetivo:** Conversão (venda)"),
  esp(),
  caixa("A regra que atravessa as quatro", [
    "**Em toda anatomia, exclua clientes.** Pagar para anunciar a quem já comprou é queimar verba. Aparece nas quatro anatomias e nas três camadas do perpétuo — é a única exclusão que o método trata como obrigatória em qualquer configuração.",
  ]),
  h2("Quadro comparativo das 4 anatomias"),
  tabela(
    ["", "Descoberta", "Relacionamento", "Conversão", "Remarketing"],
    [
      ["**Gancho**", "Indireto ou direto", "Indireto ou direto", "Direto", "Direto/indireto + prontidão"],
      ["**CTA**", "Siga, comente, compartilhe", "Comente, compartilhe", "Saiba mais, entenda, aula gratuita", "Compre, garanta"],
      ["**Inclui**", "Interesses, lookalike, aberto", "Seguidores e listas", "Interesses + lookalike + aberto + listas", "Quem entrou na PV"],
      ["**Exclui**", "Seguidores, listas, clientes", "Clientes", "Clientes", "Clientes"],
      ["**Objetivo**", "Views 50/90% ou Seguidores", "Views 50/90%", "Conversão (lead ou venda)", "Conversão (venda)"],
    ],
    [1300, 1980, 1780, 2200, 1760],
  ),
  h2("As 18 limitações criativas"),
  p("Aqui está o dispositivo mais útil do método para produção em volume. Quando travar em “o que eu gravo?”, você **escolhe uma limitação e escreve dentro dela**. A restrição é o que gera volume criativo — parece contraintuitivo e é exatamente o oposto: liberdade total paralisa, restrição produz."),
  tabela(
    ["#", "Tipo", "#", "Tipo"],
    [
      ["1", "Comparação", "10", "Apelo ao visual"],
      ["2", "Problema / Solução", "11", "Oportunidade"],
      ["3", "Explicação", "12", "História"],
      ["4", "Curiosidade", "13", "Dilema"],
      ["5", "Apelo emocional", "14", "Prova"],
      ["6", "Reflexão", "15", "Contraste"],
      ["7", "Certo x errado", "16", "Clickbait"],
      ["8", "Demonstração", "17", "Sensação"],
      ["9", "Ultra segmentado", "18", "Mito"],
    ],
    [700, 3810, 700, 3810],
  ),
  esp(),
  h3("Como escolher a limitação para um nicho técnico"),
  p("Não todas rendem igual em todo nicho. Para um produto técnico como um curso de cálculo luminotécnico, as que mais rendem são seis:"),
  tabela(
    ["Limitação", "Como fica na prática"],
    [
      ["**Demonstração**", "A tela do software calculando"],
      ["**Certo x errado**", "Projeto no achismo vs projeto calculado"],
      ["**Contraste**", "Render antes/depois"],
      ["**Prova**", "Projeto real entregue"],
      ["**Mito**", "“Spot a cada 1,5 m” é regra? Não é"],
      ["**Ultra segmentado**", "“Se você é arquiteto de interiores…”"],
    ],
    [2300, 6720],
  ),
  h2("O processo, em 7 passos"),
  ol("Definir **qual anatomia** (descoberta / relacionamento / conversão / remarketing)."),
  ol("Escolher **1 limitação criativa**."),
  ol("Escrever o **gancho** — indireto ou direto; se direto, escolher dúvida, dor ou desejo."),
  ol("Aplicar o **filtro de copy** na primeira linha."),
  ol("**Desenvolvimento** — entregar o que o gancho prometeu."),
  ol("**CTA** compatível com a anatomia (não peça “compre” num anúncio de descoberta)."),
  ol("Definir **público e objetivo** conforme a anatomia."),
  esp(),
  caixa("A instrução que muda a produção", [
    "Ao gerar criativos, produza **várias variações mudando só a limitação criativa** — mesma oferta, ângulos diferentes.",
    "É assim que se acha o criativo vencedor **sem reinventar a oferta**. E é o que torna o teste legível: se você troca a oferta a cada anúncio, não sabe o que ganhou.",
  ]),
  h2("Checklist do criativo"),
  li("A anatomia escolhida bate com o público e o objetivo de campanha"),
  li("O CTA é compatível com a anatomia"),
  li("Clientes estão excluídos do público"),
  li("A primeira linha filtra o público"),
  li("O gancho tem urgência oculta clara (dúvida, dor ou desejo)"),
  li("O desenvolvimento entrega o que o gancho prometeu"),
  li("Nenhuma promessa sem lastro real"),
  h2("O agente do curso"),
  p("O curso disponibiliza um assistente de GPT chamado **Agente de Mandala de Anúncios**, que operacionaliza justamente essa combinatória de anatomia + limitação criativa. Ele está referenciado no mapa mental da aula 02 e na skill de anúncios."),
  quebra(),
);

// ============================== PARTE 7 — ESTRATÉGIA ==============================
add(
  h1("Parte 7 — Estratégia de tráfego pago"),
  p("Fonte: módulos 4 (Fluxos de Venda, 22 aulas) e 7 (Tráfego Pago, 29 aulas). Este capítulo é sobre **o que montar e por quê**. A execução no Meta Ads está na Parte 8."),
  h2("Primeiro: escolher o fluxo, não a campanha"),
  p("O erro comum é começar pela campanha. Comece pelo **fluxo de venda** — ele determina todo o resto: o objetivo, o público, o criativo, a página de destino e a métrica que importa."),
  tabela(
    ["Fluxo", "Quando usar"],
    [
      ["**Conversão direta**", "Ticket baixo, oferta simples. Anúncio → página → checkout"],
      ["**Conversão + remarketing**", "O básico de qualquer perpétuo: quem visitou e não comprou volta a ver anúncio"],
      ["**Isca digital**", "Ticket médio/alto, ou quando o público ainda não sabe que tem o problema"],
      ["**Webinário**", "Ticket alto, oferta que precisa de explicação longa"],
      ["**Quiz**", "Quando a segmentação muda a oferta"],
      ["**WhatsApp**", "Venda consultiva, ticket alto"],
      ["**Pré-checkout e recuperação**", "Sempre. Carrinho abandonado é a venda mais barata"],
    ],
    [2600, 6420],
  ),
  esp(),
  p("**Regra prática de ticket:** ticket baixo aguenta conversão direta — mandar o anúncio direto para a página funciona. Isca digital e webinário fazem mais sentido conforme o ticket sobe."),
  p("O módulo 4 vai muito além destes sete: tem fluxo mandala, native ads, pico sem página de vendas, pico direto, pico fechado, pico aberto, upsell, downsell, orderbump, assinatura e recorrência, SaaS e high ticket. Para conteúdo, os sete acima cobrem 90% dos casos que o ouvinte vive."),
  caixa("A venda mais barata que existe", [
    "**Pré-checkout e recuperação: sempre.** Não é um fluxo alternativo — é um fluxo que roda por cima de qualquer outro. Carrinho abandonado é a venda mais barata do negócio, porque a pessoa já se convenceu; ela só travou no meio.",
  ]),
  h2("As três camadas do perpétuo"),
  p("Aqui está o conceito estrutural mais importante da Parte 7: **perpétuo não é uma campanha, são três rodando ao mesmo tempo**."),
  tabela(
    ["Camada", "Objetivo", "Público", "O que o anúncio faz"],
    [
      ["**Distribuição**", "Alcance / views", "Interesses, lookalike, aberto · exclui seguidores e clientes", "Entrega conteúdo, gera reconhecimento"],
      ["**Conversão**", "Lead ou venda", "Interesses + lookalike + seguidores e listas mornas · exclui clientes", "Leva para a página"],
      ["**Remarketing**", "Venda", "Quem entrou na página · exclui clientes", "Fecha quem já demonstrou intenção"],
    ],
    [1600, 1600, 3100, 2720],
  ),
  esp(),
  p("Compare esta tabela com o quadro das 4 anatomias, na Parte 6: elas se encaixam. A camada define **onde** o anúncio roda; a anatomia define **como** ele fala. Distribuição usa criativo de descoberta ou relacionamento; conversão usa criativo de conversão; remarketing usa criativo de remarketing, com prontidão."),
  p("O módulo 7 do curso confirma essa arquitetura na prática: há uma aula dedicada a cada camada — Campanha de Distribuição, Campanha de Conversão, Campanha de Remarketing — mais uma de Rituais e Otimização."),
  h2("Públicos: comece amplo"),
  p("**Comece amplo.** O algoritmo (Advantage+ e o motor Andromeda, que tem duas aulas dedicadas no curso, somando mais de 75 minutos) encontra melhor que segmentação manual quando há sinal de conversão suficiente. Segmentação estreita demais no início **trava o aprendizado**."),
  h3("A ordem de montagem"),
  ol("**Aberto ou interesses amplos** para distribuição."),
  ol("**Lookalike** a partir de compradores, assim que houver base."),
  ol("**Públicos de engajamento** (viu 50% ou 90% do vídeo, visitou a página) para conversão e remarketing."),
  ol("**Exclusão de clientes** em tudo."),
  esp(),
  p("E o pré-requisito duro: **sem pixel ativo e evento mapeado, nada disso funciona**. Não é recomendação — é condição de existência. Na Parte 8 isso vira um gate que impede a campanha de subir."),
  h2("Ritmo de investimento"),
  li("**Suba campanha PAUSED** e revise antes de ativar."),
  li("**Não mexa na campanha nas primeiras 48 a 72 horas.** Otimizar cedo demais reinicia o aprendizado."),
  li("**Escale devagar.** Aumento agressivo de orçamento joga a campanha de volta para aprendizado."),
  li("**Um teste por vez.** Trocar criativo e público juntos torna o resultado ilegível."),
  esp(),
  citacao("Trocar criativo e público juntos torna o resultado ilegível.", "skill trafego-estrategia"),
  h2("Rituais de otimização"),
  p("Rotina, não improviso. O que olhar, **em ordem**:"),
  ol("**CPA / CAC** contra o ticket. É o número que decide se continua."),
  ol("**CTR do criativo.** CTR baixo é problema de criativo ou de público, não de orçamento."),
  ol("**Conversão da página.** Muito clique e pouca venda = a página não sustenta a promessa do anúncio. Nesse caso o problema não é tráfego — é a página."),
  ol("**Frequência.** Subiu muito? O público saturou; troque criativo ou amplie o público."),
  ol("**Onde o funil vaza.** Compare: viu anúncio → clicou → chegou na página → iniciou checkout → comprou. A maior queda percentual é onde trabalhar."),
  h2("Métrica que importa"),
  li("**CPA** (custo por aquisição) contra o ticket e a margem."),
  li("**ROAS** só faz sentido com o custo real do produto na conta."),
  li("**CAC** contra o LTV — se há upsell, recorrência ou segundo produto, o CAC aceitável sobe."),
  esp(),
  caixa("A decisão que precede a campanha", [
    "Definir o **CPA máximo aceitável antes de subir a campanha**. Sem esse número, não existe decisão de pausar ou escalar — existe achismo.",
    "O curso tem uma aula específica de Tira-Dúvidas sobre CAC e CPA no módulo 1, e uma planilha de projeção financeira. Não é detalhe de planilha: é o que transforma “o anúncio está caro” em “o anúncio está acima do meu teto”.",
  ]),
  h2("Checklist: antes de subir qualquer campanha"),
  li("Fluxo de venda definido"),
  li("Página pronta e testada no celular"),
  li("Pixel instalado e evento de compra disparando"),
  li("CPA máximo aceitável definido"),
  li("Criativos de pelo menos 3 ângulos diferentes"),
  li("Público de exclusão de clientes montado"),
  li("Orçamento diário que suporte pelo menos 3x o CPA alvo"),
  quebra(),
);

// ============================== PARTE 8 — EXECUÇÃO ==============================
add(
  h1("Parte 8 — Execução: subir campanha no Meta Ads"),
  p("Fonte: módulo 6 (Tráfego Pago com IA) e as skills oficiais de operação do curso. Enquanto a Parte 7 decide *o que* montar, esta parte é o *como* — e é rica em conteúdo porque cada regra dela nasceu de um erro que custou dinheiro."),
  p("O curso opera isso por agente de IA, com dois escopos: **conexão** (autenticar a conta, escolher o modo de acesso) e **criação de campanha**. O que importa para o podcast não são os nomes das ferramentas, e sim os **critérios** embutidos nelas."),
  h2("Os cinco princípios que a operação nunca viola"),
  ol("**Liberdade sobre a estrutura.** Sugerir, não impor."),
  ol("**Subir sempre PAUSED por default.** Erro de configuração não vira gasto real."),
  ol("**Sem tracking, sem campanha.** Pixel ativo e evento mapeado são pré-requisitos duros."),
  ol("**Preview antes de criar. Sempre** — inclusive no modo expresso."),
  ol("**Nomenclatura consistente**, com override quando pedido."),
  esp(),
  caixa("O gate de confirmação", [
    "Toda operação que **modifica** a conta de anúncios passa por uma confirmação explícita antes de acontecer, mostrando o que vai mudar, o impacto no aprendizado e se é reversível. Leituras (listar públicos, conferir pixel, ver métricas) não passam pelo gate, porque não mudam estado.",
    "É um detalhe de engenharia com uma lição de operação embutida: **separar leitura de escrita** é o que permite trabalhar rápido sem risco.",
  ]),
  h2("Só dois objetivos de campanha"),
  p("A operação cobre exclusivamente infoprodutos, com dois objetivos:"),
  tabela(
    ["Objetivo", "Tipo de funil", "Quando"],
    [
      ["**Sales** (vendas)", "Perpétuo de venda direta", "Otimização por compra"],
      ["**Leads** (cadastros)", "Lançamento de captação", "Otimização por lead"],
    ],
    [2400, 3100, 3520],
  ),
  esp(),
  p("Awareness, Traffic, Engagement e App Promotion ficam de fora, e a recusa é explícita. Isso é uma escolha de método, não uma limitação técnica: para infoproduto de perpétuo, otimizar por alcance ou por clique é comprar o número errado."),
  h2("As 9 fases da montagem"),
  h3("Fase 1 — Objetivo e tipo de funil"),
  p("Venda direta ou captação de leads. Define o objetivo da campanha e toda a cadeia seguinte."),
  h3("Fase 2 — Produto e ticket"),
  p("O ticket serve para três coisas: classificar a trilha (baixo, médio, alto), que define as janelas e as referências de CPA; compor a nomenclatura; e validar a coerência do orçamento na fase 4."),
  h3("Fase 3 — Estrutura"),
  p("Aqui está uma das partes mais úteis para quem já roda tráfego: **a estrutura da campanha deve corresponder ao que você está testando**."),
  tabela(
    ["Notação", "O que é", "Use quando"],
    [
      ["**1-X-1**", "1 campanha, X conjuntos, 1 anúncio cada", "Vai testar **público**"],
      ["**1-1-X**", "1 campanha, 1 conjunto, X anúncios", "Vai testar **criativo**"],
      ["**X-1-1**", "X campanhas paralelas", "Já validou tudo e está **escalando**"],
    ],
    [1400, 3900, 3720],
  ),
  esp(),
  p("Isso amarra com a regra da Parte 7 — “um teste por vez”. A estrutura é o que torna o teste legível: se você testa criativo, mantém o público constante e varia o anúncio dentro do mesmo conjunto."),
  h3("Fase 4 — Orçamento"),
  p("Duas perguntas, sempre. Primeiro **ABO ou CBO** — orçamento por conjunto, ou orçamento na campanha distribuído pelo Meta. Depois o valor, por conjunto (ABO) ou da campanha inteira (CBO)."),
  p("E uma validação de coerência que vale citar no ar: se o orçamento diário está **abaixo do CPA alvo**, o Meta vai precisar de muitos dias para entregar a primeira conversão. O aviso é dado, mas a decisão fica com quem opera."),
  h3("Fase 5 — Tracking (o gate duro)"),
  p("A fase mais rígida. A sequência é: listar todos os pixels da conta, escolher, **salvar a escolha** para as próximas campanhas, escolher o evento de otimização (Compra, ou uma conversão personalizada) e validar na API."),
  p("Duas validações antes de prosseguir:"),
  li("O pixel **existe** na conta."),
  li("O evento escolhido **está recebendo dados nos últimos 7 dias**."),
  esp(),
  p("Se o pixel não existe, para tudo. Se o pixel existe mas o evento não recebeu dados em 7 dias, o aviso é honesto: o algoritmo vai otimizar por proxy até o evento começar a disparar."),
  citacao("Não aceitar Sales/Leads sem pixel. É regra dura.", "skill trafego-criar-campanha"),
  h3("Fase 6 — Público"),
  p("Três opções, com a primeira marcada como recomendada:"),
  ol("**Advantage+ Audience (recomendado).** Público 100% aberto, sem sugestões nem restrições. O Meta encontra quem converte sozinho — ideal para *descobrir* o público real do produto."),
  ol("**Advantage+ com interesses.** Mantém o Advantage+ como base e adiciona interesses como sugestão: não restringe, só orienta o algoritmo no início."),
  ol("**Personalizado.** Combinação livre: públicos customizados, lookalikes, interesses específicos, idade, localização, exclusões. Use quando já validou um público que converte, ou quando precisa restringir por motivo de negócio."),
  esp(),
  p("O detalhe metodológico da opção 1 é a frase “descobrir o público real do produto”. Ela reconhece algo que o mercado resiste a aceitar: **você provavelmente não sabe quem é seu público** — e o algoritmo descobre mais rápido que a sua persona."),
  h4b("Como se monta a lista de interesses, quando se opta por ela"),
  p("O procedimento é instrutivo mesmo para quem não usa ferramenta nenhuma:"),
  ol("Levantar o perfil: nicho, principal transformação (verbo + objeto), e 5 a 10 temas que esse público consome."),
  ol("Montar 5 a 8 termos curtos em português e **traduzir para inglês** — a base de interesses do Meta é multilíngue, mas indexada melhor em inglês."),
  ol("Buscar cada termo e coletar tamanho de público."),
  ol("Filtrar: **fora** o que tem menos de 500 mil pessoas (minúsculo) e **fora** o que passa de 500 milhões (genérico demais, tipo “Comida”)."),
  ol("Deduplicar, priorizar o que bate com o nicho, e ficar com 8 a 12 interesses."),
  esp(),
  p("Os dois cortes de tamanho são o tipo de número concreto que rende no ar, porque quase ninguém segmenta com critério de tamanho — segmenta por intuição."),
  h3("Fase 7 — Criativos e copy"),
  p("Três caminhos: enviar arquivos agora, montar a estrutura e adicionar criativos depois, ou usar o que já está na biblioteca da conta."),
  p("Especificações que valem anotar:"),
  tabela(
    ["Formato", "Limite", "Resolução / duração recomendada"],
    [
      ["Imagem (JPG, PNG)", "até 30 MB", "1080×1080 (Feed), 1080×1350 (Feed vertical), 1080×1920 (Reels/Stories)"],
      ["Vídeo (MP4, MOV)", "até 4 GB (ideal < 1 GB)", "Até 60s para Reels, até 120s para Feed"],
    ],
    [2100, 2300, 4620],
  ),
  esp(),
  p("Para cada anúncio, a copy pede: headline, texto principal, descrição opcional, botão de CTA e URL de destino."),
  caixa("UTMs: nunca opcionais", [
    "A operação **sempre** aplica os parâmetros de rastreamento, sem perguntar. O padrão usa as variáveis dinâmicas do Meta para carregar nome e ID de campanha, conjunto, anúncio e posicionamento.",
    "A lição de método: se você não sabe qual anúncio gerou a venda, você não tem tráfego — tem gasto. E deixar isso na mão da decisão humana a cada campanha garante que um dia vai faltar.",
  ]),
  h3("Fase 8 — Posicionamentos"),
  p("Default: **Advantage+ Placements** (todos automáticos). Override aceito se quem opera pedir só Feed, ou só Reels e Stories."),
  h3("Fase 9 — Nomenclatura"),
  p("Padrão automático, com override:"),
  tabela(
    ["Nível", "Padrão", "Exemplo"],
    [
      ["Campanha", "[Tipo de funil] - [Produto] - [Estrutura] - [Data]", "Perpétuo - Curso X - 1-1-3 - 2026-05-04"],
      ["Conjunto", "AS - [Audiência] - [Apelido]", "AS - Advantage+ - Brasil"],
      ["Anúncio", "AD - [Ângulo] - [Formato]", "AD - Dor - Vídeo 30s"],
    ],
    [1400, 3900, 3720],
  ),
  esp(),
  p("Note o nome do anúncio: **AD - Dor - Vídeo 30s**. O “ângulo” no nome é exatamente a urgência oculta e a limitação criativa da Parte 6. A nomenclatura é o que permite, três semanas depois, saber qual ângulo ganhou."),
  h2("Preview antes de criar"),
  p("Antes de qualquer escrita na conta, um preview completo. Duas decisões interessantes de comunicação aqui: o preview técnico completo é **salvo em arquivo** para auditoria, mas o que se mostra na tela é um **resumo em texto corrido**, em português, sem código."),
  p("E uma regra que qualquer operação deveria adotar: **todo ID vem com o nome humano ao lado**, no formato Nome (ID). Nunca “Page ID 100000000000001”, sempre “Página Exemplo (100000000000001)”. É assim que se evita subir campanha na conta errada."),
  h2("Depois de criar: o que fazer"),
  ol("Acessar o Gerenciador e revisar visualmente cada anúncio — preview, copy, criativo."),
  ol("Ativar manualmente quando estiver tudo certo (a campanha nasce PAUSED)."),
  ol("Após 48 a 72 horas de veiculação, acompanhar os primeiros resultados — e não antes."),
  h2("Casos de borda que ensinam"),
  tabela(
    ["Situação", "O que a operação faz", "Por quê"],
    [
      ["Orçamento diário menor que metade do CPA alvo", "Avisa e pede confirmação, sem bloquear", "Entrega vai ser lenta demais para gerar sinal"],
      ["**Mais de 5 anúncios no mesmo conjunto**", "Sugere dividir ou priorizar 3 a 5 ângulos", "**Anúncios no mesmo conjunto disputam aprendizado entre si**"],
      ["Imagem com muito texto", "Avisa, sem bloquear", "A regra antiga de rejeição caiu, mas Reels pode performar pior"],
      ["Campanha com nome similar ativa há menos de 7 dias", "Pergunta se prossegue, renomeia ou cancela", "Evita duplicar concorrência interna"],
      ["Falha ao criar um anúncio", "Preserva o que já subiu e relata", "Rollback total costuma destruir trabalho bom"],
      ["Pedido para ativar imediatamente", "Aceita, mas confirma antes", "“Uma vez ativa, começa a gastar”"],
    ],
    [2500, 3200, 3320],
  ),
  esp(),
  caixa("O achado mais contraintuitivo da Parte 8", [
    "**Mais de 5 anúncios no mesmo conjunto disputam aprendizado entre si.**",
    "Ou seja: subir 12 criativos de uma vez, achando que está testando mais rápido, faz o oposto — fragmenta o orçamento e nenhum dos 12 acumula sinal suficiente para sair do aprendizado. O método sugere 3 a 5 ângulos por conjunto. É um ótimo bloco de episódio, porque contradiz o instinto de “quanto mais criativo, melhor”.",
  ]),
  h2("Sobre a operação por IA, sem hype"),
  p("O curso tem um módulo inteiro (o 6) sobre operar tráfego com IA, e uma aula chamada “O que mudou com a IA no Meta ADS”. A honestidade do material está em reconhecer onde a automação **não** chega: há operações que a integração não faz (subir arquivo local de imagem ou vídeo, buscar interesse por nome, criar lookalike) e, nesses casos, o protocolo é explícito — avisar, oferecer o caminho manual, ou pedir autorização para um modo de acesso mais amplo."),
  p("Traduzindo para conversa de podcast: **automação boa é a que declara o que não sabe fazer**. A que finge cobrir tudo é a que quebra em produção."),
  quebra(),
);

function h4b(t) { return H.h3(t); }

module.exports = H;
