// Dossiê VTSD — conteúdo (partes 9 a 16) + montagem do documento
const H = require("./gen3.js");
const { add, h1, h2, h3, p, li, ol, citacao, caixa, tabela, esp, quebra, legenda, children } = H;
const {
  Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel,
  LevelFormat, BorderStyle,
} = H;

// ============================== PARTE 9 — ORGÂNICO ==============================
add(
  h1("Parte 9 — Conteúdo orgânico: a usina de criativos"),
  p("Fonte: módulo 8 (Conteúdo, 18 aulas). Este capítulo fecha o circuito: o que performa organicamente **vira criativo pago**, e quem assiste vira público de remarketing. Orgânico e pago não são canais separados — são o mesmo motor em duas rotações."),
  h2("Linha editorial vem antes do formato"),
  p("O erro comum é escolher formato (“vou fazer um Reel”) antes de decidir o que a conta defende. A linha editorial responde três coisas: **sobre o que você fala, contra o que você fala, e o que você nunca fala**."),
  p("Um exemplo de três eixos que sustentam a venda de um curso técnico sem parecer propaganda:"),
  tabela(
    ["Eixo", "Conteúdo", "Função na venda"],
    [
      ["**Técnico**", "Cálculo, norma, lux vs lúmen, IRC, UGR", "Prova de autoridade — sustenta o preço"],
      ["**Crítico**", "Projeto no achismo, erros comuns, mitos do mercado", "Cria o inimigo comum e a urgência"],
      ["**Resultado**", "Antes/depois, projeto entregue, bastidor", "Prova visual e desejo"],
    ],
    [1400, 3600, 4020],
  ),
  esp(),
  p("A regra é seca: todo conteúdo deve caber em um dos eixos. Se não cabe, não é da conta."),
  p("Repare que os três eixos são os três elementos da persuasão da Parte 3 em forma de calendário: técnico é **credibilidade**, crítico é **emoção**, resultado é **lógica** e prova ao mesmo tempo."),
  h2("Os 7 formatos de Reels"),
  p("O curso destrincha sete formatos, um por aula. Use como cardápio quando travar:"),
  tabela(
    ["Formato", "O que é", "Exemplo aplicado"],
    [
      ["**Histórias pessoais**", "Narrativa própria", "“O projeto que eu refiz três vezes”"],
      ["**Trends e opiniões**", "Pegar assunto do momento e opinar", "Opinar sobre a iluminação de um projeto viral"],
      ["**POV e memes**", "Humor de nicho", "POV: o cliente pediu “luz aconchegante”"],
      ["**Cortes de podcast**", "Recorte de fala longa", "Cortes das suas lives e vídeos longos"],
      ["**Caixinha de perguntas**", "Responder pergunta real", "Dúvidas que chegam na DM"],
      ["**Perguntas e respostas**", "Formato direto de dúvida", "“Lux ou lúmen?”"],
      ["**Problema × Solução**", "O mais direto para conversão", "“Sala escura mesmo com 12 spots. O erro é…”"],
    ],
    [2000, 2900, 4120],
  ),
  esp(),
  p("**Stories** é aula à parte no curso, com 25 minutos — é onde mora o relacionamento diário e a venda mais direta."),
  caixa("Para este projeto especificamente", [
    "“Cortes de podcast” é um dos sete formatos oficiais do método. Ou seja: o próprio podcast que este dossiê alimenta é, por construção, uma **fábrica de criativos**. Cada episódio gera cortes; cada corte que performa organicamente é candidato a anúncio de descoberta.",
  ]),
  h2("As 4 Lives"),
  li("**Tipos e temas** — a estrutura geral de quando e sobre o que fazer live."),
  li("**Entrevista com alunos** — prova social ao vivo. É o depoimento mais difícil de falsificar."),
  li("**Entrevista com autoridades** — empresta autoridade de terceiros."),
  li("**Consultoria aleatória** — resolve o problema de alguém ao vivo. Demonstra competência melhor que qualquer argumento."),
  esp(),
  p("Para produto técnico, “consultoria aleatória” é o formato mais forte de todos: abrir o software e resolver o projeto de um seguidor ao vivo **é** a demonstração do produto. É o mecanismo único (Parte 2) e o bloco de demonstração do VSL (Parte 5) acontecendo em tempo real, sem edição."),
  h2("YouTube: dois jogos diferentes"),
  p("Quatro frentes no curso — fundamentos, SEO, recomendados e linha editorial. E a distinção que organiza tudo:"),
  tabela(
    ["Jogo", "Atende quem", "Métrica que manda", "Efeito"],
    [
      ["**SEO**", "Quem já procura (“como usar o software X”)", "Título, descrição, palavra-chave", "Converte bem, cresce devagar"],
      ["**Recomendados**", "Quem nem sabia que queria", "Retenção, CTR, tempo de sessão", "Cresce rápido, converte pior"],
    ],
    [1600, 3000, 2400, 2020],
  ),
  esp(),
  p("Um canal que só faz SEO cresce devagar; um que só faz recomendado não converte. **Precisa dos dois** — e a linha editorial do YouTube é diferente da do Instagram, porque aqui a intenção de busca manda."),
  h2("Da audiência para a venda"),
  p("O elo explícito entre as Partes 6, 7 e 9:"),
  li("Conteúdo que performa organicamente é candidato natural a **anúncio de descoberta**."),
  li("Quem assistiu 50% ou 90% vira público de **relacionamento**."),
  li("Quem clicou e foi à página vira público de **remarketing**."),
  esp(),
  p("É por isso que a Parte 7 manda montar públicos de engajamento por percentual de vídeo assistido: o número 50/90% que aparece no objetivo de campanha das anatomias de descoberta e relacionamento é exatamente o que constrói o público da camada seguinte."),
  h2("Roteiro de Reel, em 5 passos"),
  ol("Escolher **eixo** e **formato**."),
  ol("**Gancho nos 3 primeiros segundos** — mesma lógica do anúncio: dúvida, dor ou desejo."),
  ol("**Filtro de público** logo no início."),
  ol("Entregar o que o gancho prometeu."),
  ol("CTA compatível: orgânico pede *siga / comente / salva*, não *compre*."),
  esp(),
  p("A simetria com a Parte 6 é total — e é de propósito. O que muda entre um Reel orgânico e um anúncio de descoberta é o CTA e o fato de um ser pago. A gramática é a mesma."),
  h2("Roteiro de vídeo de YouTube, em 4 passos"),
  ol("Validar demanda de busca **antes de gravar**."),
  ol("Decidir se é jogo de **SEO** ou de **Recomendados**."),
  ol("**Título e thumb antes do roteiro** — se não dá título bom, o tema é fraco."),
  ol("Roteiro com retenção: entregar valor cedo, não guardar tudo para o fim."),
  esp(),
  caixa("A regra que economiza mais tempo", [
    "**Título e thumbnail antes do roteiro.** Se você não consegue escrever um título bom para o tema, o tema é fraco — e você descobre isso em dois minutos, não depois de gravar quarenta.",
  ]),
  quebra(),
);

// ============================== PARTE 10 — TRANSCRIÇÃO ==============================
add(
  h1("Parte 10 — Swipe file e reaproveitamento"),
  p("O curso entrega **30 páginas de vendas reais e 33 anúncios de referência** como material de estudo, separados em anúncios de descoberta e de relacionamento. É o ativo mais subaproveitado do curso, e o método é explícito: **leia pelo menos uma referência do mesmo formato antes de propor estrutura**."),
  h2("Como se estuda um swipe file de anúncio"),
  p("Não é para copiar. É para **classificar**. O procedimento que funciona:"),
  ol("Transcreva o anúncio para texto — o gancho fica visível quando você o lê em vez de ouvir."),
  ol("Classifique por **anatomia** (descoberta, relacionamento, conversão, remarketing)."),
  ol("Classifique por **limitação criativa** (uma das 18)."),
  ol("Identifique o **tipo de gancho** (indireto, ou direto com dúvida/dor/desejo)."),
  ol("Marque onde está o **filtro de público** — e em quantos segundos ele aparece."),
  esp(),
  p("Ao fim de 33 anúncios classificados assim, você tem um mapa de qual combinação de anatomia e limitação criativa o mercado mais usa — e, mais interessante para conteúdo, quais das 18 limitações quase ninguém usa."),
  h2("Transcrição local, sem custo"),
  p("Existe uma peça de ferramenta neste conjunto que merece nota porque muda a economia do reaproveitamento: transcrição rodando **100% na máquina**, sem chave de API e sem enviar arquivo para fora. Modelo pequeno roda a cerca de 3x o tempo real em CPU; modelos maiores, mais lentos, para áudio ruim ou muito jargão técnico."),
  p("Saída em dois formatos por arquivo: um markdown com marcação de tempo e um arquivo de legenda pronto para subir."),
  h3("Os três usos"),
  li("**Seus próprios vídeos** — o conteúdo já está gravado; transcrever é reaproveitar. Vira Reel, carrossel, e-mail e seção de página de vendas."),
  li("**Swipe file de anúncios** — transcrever as referências para estudar o gancho em texto."),
  li("**Aulas e calls** — qualquer gravação de aula, mentoria ou reunião."),
  esp(),
  caixa("Limite que o próprio material impõe", [
    "Ferramenta de download de vídeo público não se usa para conteúdo protegido por login ou DRM de plataforma paga. Os vídeos de área de membros costumam ter marca d’água com o ID do usuário, e os termos de uso proíbem download.",
    "Para estudar o curso, o caminho é o material escrito — apostilas e mapas mentais — que é o mesmo conteúdo já editado e estruturado, e melhor para consulta.",
  ]),
  h2("A regra de ouro do reaproveitamento"),
  citacao("A transcrição bruta é insumo, não entregável."),
  p("Toda transcrição precisa passar por um filtro antes de virar peça: copy (se vai virar texto), criativo (se vai virar anúncio) ou linha editorial (se vai virar post). Transcrição publicada crua é a forma mais rápida de produzir conteúdo que ninguém consome."),
  quebra(),
);

// ============================== PARTE 11 — CHEAT SHEETS ==============================
add(
  h1("Parte 11 — Referência rápida"),
  p("Os quadros abaixo condensam o método em formato de consulta. Servem para checar um número no meio de uma gravação sem procurar no capítulo."),
  h2("As três tríades do método"),
  p("Uma curiosidade estrutural que vale contar no ar: o método se repete em tríades, e elas se espelham."),
  tabela(
    ["Tríade", "Elementos", "Onde aparece"],
    [
      ["Fundamentos do texto", "Coesão · Coerência · Simplicidade", "Copywriting"],
      ["Elementos da persuasão", "Lógica · Emoção · Credibilidade", "Copy, página, VSL"],
      ["Urgências ocultas", "Dúvida · Dor · Desejo", "Produto, anúncio, VSL, Reel"],
      ["Camadas do perpétuo", "Distribuição · Conversão · Remarketing", "Estratégia de tráfego"],
      ["Anatomia da seção", "Headline · Subheadline · Conteúdo", "Página de vendas"],
      ["Estrutura do anúncio", "Gancho · Desenvolvimento · CTA", "Criativos"],
    ],
    [2300, 3800, 2920],
  ),
  h2("Números para ter na ponta da língua"),
  tabela(
    ["Número", "O que é"],
    [
      ["**12 palavras**", "Máximo de uma headline de página de vendas"],
      ["**25 palavras**", "Máximo de uma subheadline"],
      ["**60 palavras**", "Máximo do corpo de uma seção — passou disso, vira lista"],
      ["**15 palavras**", "Máximo de um item de lista"],
      ["**3 linhas**", "Máximo de um parágrafo, e nunca dois longos seguidos"],
      ["**8+**", "CTAs ao longo da página (não 3)"],
      ["**16**", "Seções disponíveis de página de vendas"],
      ["**4**", "Anatomias de criativo"],
      ["**18**", "Limitações criativas"],
      ["**26**", "Gatilhos mentais"],
      ["**5**", "Itens da régua de Blair Warren"],
      ["**3 a 5**", "Gatilhos a escolher por peça (não todos)"],
      ["**3 a 5**", "Anúncios por conjunto — mais que 5 disputam aprendizado"],
      ["**15 segundos**", "Bloco de gancho do VSL, sem introdução"],
      ["**4 minutos**", "VSL de venda direta, ticket baixo"],
      ["**3 segundos**", "Gancho de Reel"],
      ["**48 a 72 horas**", "Período em que não se mexe na campanha nova"],
      ["**3x o CPA alvo**", "Orçamento diário mínimo recomendado"],
      ["**7 dias**", "Janela em que o evento do pixel precisa ter recebido dados"],
      ["**500 mil / 500 milhões**", "Piso e teto de tamanho de interesse utilizável"],
      ["**50% e 90%**", "Percentuais de vídeo assistido que definem público de engajamento"],
      ["**60 a 90 segundos**", "Duração pedida a quem grava depoimento"],
      ["**10 a 15 pessoas**", "Tamanho de um beta pago para colher prova real"],
      ["**150 aulas / 11 módulos**", "Tamanho do curso"],
    ],
    [2500, 6520],
  ),
  h2("Regras duras (as que não têm exceção)"),
  li("Nunca inventar número, depoimento, resultado ou prova."),
  li("Excluir clientes de todos os públicos pagos."),
  li("Sem pixel ativo e evento mapeado, não sobe campanha de venda ou de lead."),
  li("Subir campanha PAUSED e revisar antes de ativar."),
  li("Em perpétuo, nada de escassez artificial — contador, vaga limitada, “últimas horas”."),
  li("O inimigo é sempre uma prática, nunca uma pessoa ou empresa."),
  li("Um teste por vez."),
  li("Nunca imitar marca registrada de terceiro."),
  h2("Diagnóstico rápido de sintomas"),
  tabela(
    ["Sintoma", "Onde está o problema", "O que fazer"],
    [
      ["CTR baixo", "Criativo ou público", "Trocar ângulo (limitação criativa) ou ampliar público"],
      ["Muito clique, pouca venda", "Página", "Auditar a página — ela não sustenta a promessa do anúncio"],
      ["Frequência subindo", "Público saturado", "Trocar criativo ou ampliar público"],
      ["CPA acima do teto", "Depende de onde o funil vaza", "Comparar as etapas e atacar a maior queda percentual"],
      ["Página com muito acesso e pouco scroll", "Densidade e ritmo", "Cortar texto, virar lista, adicionar visual e CTA"],
      ["Ninguém pede o link", "Filtro de público ausente", "Dizer para quem é na primeira linha"],
      ["Público técnico desconfia", "Prova ou ancoragem", "Trocar stack monetário por benefício; ancorar no que o produto entrega"],
      ["Não sei o que gravar", "Falta de restrição", "Escolher uma das 18 limitações criativas e escrever dentro dela"],
    ],
    [2400, 2400, 4220],
  ),
  quebra(),
);

// ============================== PARTE 12 — INTERLIGAÇÕES ==============================
add(
  h1("Parte 12 — Mapa de interligações"),
  p("Este é o capítulo que transforma o dossiê em conversa. Cada linha abaixo é uma ponte entre dois pontos do método — e ponte é onde nasce o bom conteúdo, porque é o que o ouvinte não consegue montar sozinho lendo cada tema isolado."),
  h2("As pontes principais"),
  tabela(
    ["De", "Para", "A ponte"],
    [
      ["Urgências ocultas (produto)", "Gancho direto (criativo)", "Os três sabores — dúvida, dor, desejo — são os mesmos. O que se descobre na concepção do produto é literalmente o que se fala no anúncio."],
      ["Blair Warren (copy)", "Blocos 2 e 3 do VSL", "“Confirma a suspeita” e “justifica o fracasso” são dois itens da régua virando dois blocos de roteiro, em sequência."],
      ["Mecanismo único (produto)", "Demonstração (VSL e página)", "O mecanismo só existe se for demonstrável. A seção de demonstração é o mecanismo na tela."],
      ["4 anatomias (criativo)", "3 camadas (tráfego)", "A camada define onde o anúncio roda; a anatomia define como ele fala. Distribuição usa descoberta/relacionamento; conversão usa conversão; remarketing usa remarketing."],
      ["Objetivo Views 50/90% (criativo)", "Público de engajamento (tráfego)", "Otimizar por 50% ou 90% de vídeo assistido é o que constrói o público morno da camada seguinte. O objetivo de hoje é o público de amanhã."],
      ["Filtro de público (copy)", "Custo de mídia (tráfego)", "Dizer para quem é na primeira linha faz quem não é do público sair — e você deixa de pagar pela visualização irrelevante."],
      ["Conteúdo orgânico", "Anúncio de descoberta", "O que performa de graça é candidato natural a pago. O orgânico é o laboratório de criativo mais barato que existe."],
      ["Cortes de podcast (orgânico)", "Este dossiê", "“Cortes de podcast” é um dos 7 formatos oficiais de Reels. O podcast é, por construção, uma fábrica de criativos."],
      ["Ticket (produto)", "Mostrar ou omitir preço", "A mesma regra atravessa página de vendas, VSL e escolha de fluxo de venda: baixo expõe, alto conversa."],
      ["Perpétuo x lançamento (produto)", "Proibição de escassez (página)", "Se o produto vende todo dia, contador regressivo é mentira — e público técnico reconhece."],
      ["Limitação criativa (criativo)", "Nomenclatura do anúncio (execução)", "O “ângulo” no nome AD - Dor - Vídeo 30s é a urgência oculta mais a limitação criativa. É o que permite saber, três semanas depois, qual ângulo ganhou."],
      ["Um teste por vez (tráfego)", "Estrutura 1-X-1 / 1-1-X (execução)", "A estrutura da campanha é o que torna o teste legível: testa público variando conjunto, testa criativo variando anúncio."],
      ["3 elementos da persuasão (copy)", "3 eixos da linha editorial (orgânico)", "Técnico é credibilidade, crítico é emoção, resultado é lógica e prova. O calendário de conteúdo é a tríade da persuasão distribuída no tempo."],
      ["Consultoria aleatória (live)", "Demonstração (VSL)", "Resolver o problema de um seguidor ao vivo é a demonstração do produto acontecendo sem edição."],
      ["Prova de trabalho (página)", "Eixo resultado (orgânico)", "Quando não há depoimento de aluno, o projeto entregue é a prova — e ele também é pauta de conteúdo."],
    ],
    [2100, 2100, 4820],
  ),
  h2("O circuito completo, em uma volta"),
  p("Se você quiser contar o método inteiro em três minutos, conte a volta do circuito:"),
  ol("Você descobre a **urgência oculta** do seu público ao conceber o produto."),
  ol("Ela vira o **gancho** do criativo e a **abertura** do VSL."),
  ol("O criativo de descoberta leva a **views**, que constroem o público de **relacionamento**."),
  ol("O criativo de conversão leva à **página**, que constrói o público de **remarketing**."),
  ol("O remarketing fecha a venda, e o comprador **sai de todos os públicos** — porque anunciar para quem já comprou é queimar verba."),
  ol("O comprador vira **depoimento**, que vira **prova** na página, que aumenta a conversão do mesmo tráfego."),
  ol("E o conteúdo que você gravou para explicar tudo isso vira **corte**, que vira **criativo de descoberta** — e a volta começa de novo, mais barata."),
  esp(),
  caixa("Por que essa volta é o melhor conteúdo do dossiê", [
    "Porque ela mostra que o método é **cumulativo**, não linear. Cada volta do circuito deixa três ativos para trás: um público mais qualificado, uma prova nova e um criativo testado. Quem está no mês doze paga menos pelo mesmo resultado que quem está no mês um — e não é porque aprendeu a negociar com o Meta.",
  ]),
  quebra(),
);

// ============================== PARTE 13 — EPISÓDIOS ==============================
add(
  h1("Parte 13 — Roteiro sugerido de episódios"),
  p("Doze episódios cobrindo o dossiê inteiro, cada um com gancho de abertura, blocos e o material deste documento que o alimenta. A ordem segue a lógica do método, mas os episódios 5, 6 e 11 funcionam soltos, se você precisar de um episódio avulso."),
  h2("Episódio 1 — O erro que faz todo tráfego parecer caro"),
  li("**Gancho:** “Se você acha que seu anúncio está caro, existe 80% de chance de o problema não estar no anúncio.”"),
  li("**Blocos:** a ordem que não se inverte · o diagnóstico ao contrário · os dois sinais (CTR baixo vs muito clique e pouca venda)."),
  li("**Fonte:** Parte 1."),
  h2("Episódio 2 — Posicionamento é contra o que você é comparado"),
  li("**Gancho:** “Seu produto não compete com quem você pensa que ele compete.”"),
  li("**Blocos:** situação antes de posicionamento · o exemplo do curso de software vs tutorial gratuito · as duas identidades · escada sem canibalização."),
  li("**Fonte:** Parte 2."),
  h2("Episódio 3 — A furadeira e o mecanismo único"),
  li("**Gancho:** “Ninguém quer a furadeira. Mas todo mundo para de comprar o furo quando não entende por que o seu é diferente.”"),
  li("**Blocos:** mecanismo único (nome próprio, por que os outros falham, demonstrável) · QFD · o teste do mecanismo."),
  li("**Fonte:** Parte 2."),
  h2("Episódio 4 — O que ninguém fala sobre copy"),
  li("**Gancho:** “Antes de gatilho mental, existe uma coisa que salva ou mata qualquer texto — e não está em nenhum curso de copy.”"),
  li("**Blocos:** coesão, coerência, simplicidade · os 3 elementos da persuasão e o sintoma de cada ausência · Kahneman."),
  li("**Fonte:** Parte 3."),
  h2("Episódio 5 — A régua de Blair Warren (episódio avulso)"),
  li("**Gancho:** “Existem cinco coisas que fazem alguém confiar em você. Duas delas resolvem quase tudo.”"),
  li("**Blocos:** as cinco · as duas que mais rendem · por que o inimigo nunca pode ser uma pessoa · aplicação em público técnico."),
  li("**Fonte:** Parte 3."),
  h2("Episódio 6 — Página de vendas não é documento (episódio avulso)"),
  li("**Gancho:** “O erro número um de quem gera página com IA: sai um documento, não uma página.”"),
  li("**Blocos:** os limites de palavras · a escala de preferência · peso das seções · 8 CTAs, não 3 · o teste dos dez segundos."),
  li("**Fonte:** Parte 4."),
  h2("Episódio 7 — O bônus que vale tempo, não dinheiro"),
  li("**Gancho:** “Somar R$ 2.891 em bônus e cobrar R$ 297 é a forma mais rápida de perder um cliente formado.”"),
  li("**Blocos:** por que o stack monetário quebra · bônus por benefício com selo · onde entra a ancoragem de valor · a ancoragem precisa ser exatamente o que o produto entrega."),
  li("**Fonte:** Parte 4."),
  h2("Episódio 8 — Prova quando você não tem nenhum aluno"),
  li("**Gancho:** “Produto novo não tem depoimento. E as duas saídas mais comuns — inventar ou deixar vazio — são as duas piores.”"),
  li("**Blocos:** a ordem de preferência da prova · prova de trabalho · beta pago de 10 a 15 pessoas · o roteiro de depoimento em 3 perguntas e por que a primeira é a que converte."),
  li("**Fonte:** Parte 4."),
  h2("Episódio 9 — As 4 anatomias de criativo"),
  li("**Gancho:** “Existem quatro tipos de anúncio. Pedir ‘compre’ no tipo errado é jogar dinheiro fora.”"),
  li("**Blocos:** gancho indireto vs direto · as três urgências ocultas · o filtro de copy · as quatro anatomias com CTA, público e objetivo · a exclusão de clientes."),
  li("**Fonte:** Parte 6."),
  h2("Episódio 10 — As 18 limitações criativas"),
  li("**Gancho:** “A pergunta ‘o que eu gravo hoje?’ não se resolve com inspiração. Se resolve com restrição.”"),
  li("**Blocos:** por que restrição gera volume · as 18 · as seis que mais rendem em nicho técnico · a instrução de variar só a limitação e manter a oferta."),
  li("**Fonte:** Parte 6."),
  h2("Episódio 11 — Perpétuo são três campanhas (episódio avulso)"),
  li("**Gancho:** “Perpétuo não é uma campanha. São três rodando ao mesmo tempo — e quem roda uma só acha que tráfego não funciona.”"),
  li("**Blocos:** escolher o fluxo antes da campanha · as três camadas · comece amplo · o ritmo (48 a 72h, escalar devagar, um teste por vez) · os rituais em ordem · CPA máximo antes de subir."),
  li("**Fonte:** Parte 7."),
  h2("Episódio 12 — O que a operação real ensina"),
  li("**Gancho:** “Subir 12 criativos de uma vez não é testar mais rápido. É garantir que nenhum dos 12 vai aprender.”"),
  li("**Blocos:** subir PAUSED · sem pixel não sobe · as estruturas 1-X-1 e 1-1-X · ABO vs CBO · os cortes de 500 mil e 500 milhões · UTM nunca opcional · mais de 5 anúncios disputam aprendizado · automação boa é a que declara o que não sabe fazer."),
  li("**Fonte:** Parte 8."),
  esp(),
  h2("Bônus — dois episódios de fechamento"),
  li("**O circuito completo** — a volta inteira da Parte 12, do produto ao corte de podcast que volta a ser criativo. Bom episódio de encerramento de temporada."),
  li("**O que o método proíbe** — um episódio inteiro sobre as regras duras: não inventar prova, não usar escassez falsa, não atacar pessoas, não imitar marca. Vende confiança e diferencia o canal."),
  quebra(),
);

// ============================== PARTE 14 — FRASES ==============================
add(
  h1("Parte 14 — Frases para usar no ar"),
  p("Trechos do método que já vêm no formato de fala. Use como abertura de bloco, corte para Reels ou fechamento de episódio."),
  h2("Sobre copy"),
  li("“Copy é a arte de transformar letras em número.”"),
  li("“O cérebro odeia pensar. Ele prefere decidir sentindo.”"),
  li("“As pessoas tomam decisões com emoção e justificam com lógica.” (Kahneman)"),
  li("“Simplicidade não é mediocridade, é maturidade.”"),
  li("“Um texto sem coesão, coerência e simplicidade não é salvo por gatilho nenhum.”"),
  li("“A emoção abre a porta; a lógica dá permissão para comprar.”"),
  li("“Gatilho não é tempero polvilhado no fim — é estrutura.”"),
  h2("Sobre página de vendas"),
  li("“O objetivo da página não é vender. É fazer a pessoa ler a próxima linha.”"),
  li("“Cada linha vende a linha seguinte.”"),
  li("“Se uma seção não empurra o leitor para a seguinte, ela está sobrando.”"),
  li("“Página de vendas é escaneada, não lida.”"),
  li("“O produto vale dinheiro; os bônus valem tempo.”"),
  li("“A ausência de contador regressivo não é omissão. É acerto.”"),
  li("“Elogio ao professor não vende; descrição da dor anterior vende.”"),
  h2("Sobre criativo"),
  li("“O que muda entre as anatomias é o gancho, o CTA, o público e o objetivo. O resto é o mesmo.”"),
  li("“Não peça ‘compre’ num anúncio de descoberta.”"),
  li("“A restrição é o que gera volume criativo.”"),
  li("“Varie só a limitação criativa. Mesma oferta, ângulos diferentes.”"),
  li("“Quem não é do público para de assistir — e isso é bom: você deixa de pagar por view irrelevante.”"),
  h2("Sobre tráfego"),
  li("“Perpétuo não é uma campanha, são três rodando ao mesmo tempo.”"),
  li("“Pagar para anunciar a quem já comprou é queimar verba.”"),
  li("“CTR baixo é problema de criativo ou de público, não de orçamento.”"),
  li("“Muito clique e pouca venda: o problema não é tráfego, é a página.”"),
  li("“Trocar criativo e público juntos torna o resultado ilegível.”"),
  li("“Sem CPA máximo definido, não existe decisão de pausar ou escalar — existe achismo.”"),
  li("“Otimizar cedo demais reinicia o aprendizado.”"),
  li("“Diagnóstico de ‘não está vendendo’: oferta, página, criativo, público, orçamento. Quase nunca é o último.”"),
  h2("Sobre produto"),
  li("“Posicionamento não é o que o produto é. É contra o que ele é comparado.”"),
  li("“Produto certo para a situação errada não vende.”"),
  li("“Ninguém quer a furadeira; quer o furo. Mas o mecanismo único é o que explica por que o seu furo é diferente.”"),
  li("“Perpétuo e lançamento não são o mesmo produto em calendários diferentes.”"),
  li("“A escada de produtos sobe em profundidade de transformação, não em preço.”"),
  h2("Sobre operação"),
  li("“Erro de configuração não vira gasto real — se a campanha sobe pausada.”"),
  li("“Sem tracking, sem campanha.”"),
  li("“Mais de cinco anúncios no mesmo conjunto disputam aprendizado entre si.”"),
  li("“Se você não sabe qual anúncio gerou a venda, você não tem tráfego — tem gasto.”"),
  li("“Automação boa é a que declara o que não sabe fazer.”"),
  h2("Sobre ética e lastro"),
  li("“Nunca invente número, depoimento, resultado ou prova.”"),
  li("“Copy que precisa inventar não sobrevive ao primeiro cliente cético.”"),
  li("“O inimigo é sempre uma prática, nunca uma pessoa.”"),
  li("“Escassez inventada destrói confiança — e mais rápido com público técnico.”"),
  li("“A transcrição bruta é insumo, não entregável.”"),
  quebra(),
);

// ============================== PARTE 15 — LIMITES ==============================
add(
  h1("Parte 15 — Os limites: o que o método proíbe"),
  p("Vale um capítulo próprio porque é o que diferencia este método de metade do que se ensina sobre marketing digital — e porque, num podcast, falar dos limites constrói mais autoridade que falar das táticas."),
  h2("As sete proibições"),
  tabela(
    ["Proibição", "Por quê", "O que fazer no lugar"],
    [
      ["**Não inventar prova**", "Número, depoimento, resultado ou selo inventado não sobrevive ao primeiro cliente cético", "Prova de trabalho, depoimento em vídeo, beta pago de 10 a 15 pessoas"],
      ["**Não inflar stack de bônus**", "Se você não vende o bônus separado por aquele preço, o valor é ficção", "Bônus por benefício com selo, e ancoragem de valor onde o número é real"],
      ["**Não usar escassez falsa em perpétuo**", "Contador e vaga limitada em produto que vende todo dia é mentira verificável", "Argumento permanente"],
      ["**Não atacar pessoa ou empresa**", "Vira briga, não tese", "Atacar uma prática: achismo, improviso, dependência de terceiro"],
      ["**Não imitar marca de terceiro**", "Confusão de marca sugere chancela que não existe; e se a ferramenta é gratuita, herdar a cara dela desvaloriza seu conteúdo", "Identidade própria, ferramenta citada nominalmente, capturas de tela"],
      ["**Não usar logo de cliente sem autorização**", "Uso de marca precisa de permissão", "Texto genérico: “projetos entregues para incorporadoras e redes de varejo”"],
      ["**Não baixar conteúdo protegido**", "Área de membros tem marca d’água com ID do usuário e termos que proíbem download", "Usar o material escrito oficial: apostilas e mapas mentais"],
    ],
    [2400, 3400, 3220],
  ),
  h2("A regra que resume todas"),
  citacao("Nenhuma promessa sem lastro real."),
  p("Ela aparece no checklist de **todas** as skills do método — copy, página, VSL, criativo, conteúdo orgânico. É o único item que se repete integralmente em todos, e não é por acaso: num negócio de perpétuo, você vende para a mesma audiência mês após mês. Quem inventa uma vez precisa inventar sempre, e a conta chega."),
  caixa("O argumento comercial de ser honesto", [
    "Público técnico — engenheiro, arquiteto, médico, advogado — **desconta o número inflado e passa a duvidar do resto**. Ou seja: a mentira não custa só a credibilidade da afirmação mentirosa. Ela contamina as afirmações verdadeiras que estavam ao lado.",
    "É por isso que, neste método, honestidade não é postura moral. É técnica de conversão.",
  ]),
  quebra(),
);

// ============================== PARTE 16 — GLOSSÁRIO ==============================
add(
  h1("Parte 16 — Glossário"),
  p("Termos que aparecem no dossiê, na acepção que o método usa."),
  tabela(
    ["Termo", "Definição"],
    [
      ["**ABO**", "Orçamento definido em cada conjunto de anúncios (Ad Set Budget Optimization)"],
      ["**Advantage+**", "Conjunto de automações do Meta; em público, significa segmentação aberta em que o algoritmo encontra quem converte"],
      ["**Anatomia (de anúncio)**", "Uma das 4 combinações fixas de gancho, CTA, público e objetivo: descoberta, relacionamento, conversão, remarketing"],
      ["**Ancoragem de valor**", "Seção que compara o preço do produto com o valor real de mercado do serviço que o comprador vai passar a prestar"],
      ["**Andromeda**", "Motor de recomendação e leilão do Meta; tem duas aulas dedicadas no curso"],
      ["**CAC**", "Custo de aquisição de cliente; avaliado contra o LTV"],
      ["**Camada (do perpétuo)**", "Uma das 3 campanhas simultâneas: distribuição, conversão, remarketing"],
      ["**CBO**", "Orçamento definido na campanha e distribuído pelo Meta entre os conjuntos"],
      ["**CPA**", "Custo por aquisição; avaliado contra o ticket e a margem"],
      ["**CTR**", "Taxa de cliques; sintoma de qualidade de criativo ou de adequação de público"],
      ["**Filtro de copy**", "Dizer para quem a peça é na primeira linha, para que quem não é do público saia"],
      ["**Fluxo de venda**", "A arquitetura do caminho entre o anúncio e a compra; o curso cobre 22"],
      ["**Frequência**", "Quantas vezes a mesma pessoa viu o anúncio; quando sobe muito, o público saturou"],
      ["**Gancho**", "A abertura da peça. Indireto (analogia, história, curiosidade) ou direto (urgência oculta)"],
      ["**Get Views**", "Objetivo de campanha otimizado por visualização de vídeo (50% ou 90%)"],
      ["**Inimigo comum**", "A prática que o conteúdo combate; nunca uma pessoa ou empresa"],
      ["**Isca digital**", "Fluxo em que se captura o lead com material gratuito antes de ofertar"],
      ["**Limitação criativa**", "Uma das 18 restrições temáticas que se escolhe para produzir criativo em volume"],
      ["**Lookalike**", "Público semelhante a uma base existente, idealmente a de compradores"],
      ["**LTV**", "Valor total que um cliente gera ao longo do relacionamento; sustenta um CAC mais alto"],
      ["**Mecanismo único**", "O que explica por que o seu resultado é diferente do dos outros; precisa de nome próprio e de demonstração"],
      ["**PAUSED**", "Estado em que toda campanha nova é criada, para revisão antes de gastar"],
      ["**Perpétuo**", "Produto e operação que vendem todo dia, com fluxo sempre ligado"],
      ["**Pico**", "Operação de concentração de vendas em janela; o curso cobre quatro variações"],
      ["**Pixel**", "Rastreador que registra eventos no site; pré-requisito duro para campanha de venda ou lead"],
      ["**Prontidão**", "Componente exclusivo do criativo de remarketing: falar como quem retoma uma conversa"],
      ["**PV**", "Página de vendas"],
      ["**QFD**", "Quality Function Deployment: desdobrar o que o cliente diz que quer no que o produto precisa entregar"],
      ["**ROAS**", "Retorno sobre o investimento em anúncio; só é confiável com o custo real do produto na conta"],
      ["**Swipe file**", "Coleção de referências reais para estudo; o curso entrega 30 páginas e 33 anúncios"],
      ["**Trilha**", "Classificação do produto por ticket (baixo, médio, alto), que define janelas e referências de CPA"],
      ["**Urgência oculta**", "O que faz agir agora, em três sabores: dúvida, dor, desejo"],
      ["**UTM**", "Parâmetros na URL que identificam a origem do acesso; nunca opcionais"],
      ["**VSL**", "Video Sales Letter — vídeo de vendas; a aula mais longa do módulo de copy"],
    ],
    [2400, 6620],
  ),
  quebra(),
);

// ============================== PARTE 17 — FONTES ==============================
add(
  h1("Parte 17 — Fontes e proveniência"),
  p("Para você saber, ao falar no ar, de onde cada coisa veio — e o que é método do curso, o que é aprendizado de aplicação e o que é inferência."),
  h2("O que vem direto do material escrito do curso"),
  li("**Módulo 1 (Introdução)** — apostilas e planilhas: os 8 erros do perpétuo, a Teoria da Escala, CAC e CPA, projeção financeira."),
  li("**Módulo 5 (Copywriting)** — o material mais completo: apostila e mapa mental de Fundamentos de Copy; apostila e mapa mental de Anúncios, com 33 anúncios de referência; apostila e mapa mental de Página de Vendas, com 30 prints; e 7 páginas completas de alto faturamento em PDF."),
  li("**Índice das 150 aulas** — a estrutura dos 11 módulos, com duração de cada aula."),
  li("**Módulo 6 (Tráfego Pago com IA)** — as skills oficiais de conexão e de criação de campanha, que documentam o procedimento operacional completo."),
  h2("O que foi estruturado a partir dos vídeos e do índice ⚑"),
  p("Os módulos **2 (Concepção de Produto)** e **3 (Criação do Produto na Prática)** não têm apostila. Tudo o que este dossiê afirma sobre situação, posicionamento, identidades, QFD, mecanismo único e urgências ocultas foi organizado a partir do índice real das aulas e do que o material de copy do módulo 5 confirma."),
  p("Os pontos marcados com ⚑ ao longo do documento são exatamente aqueles em que vale conferir a aula em vídeo para a nuance exata do Ladeira antes de afirmar com precisão no ar. São eles: urgências ocultas, mecanismo único (a furadeira), a Teoria do QFD, e os aprendizados de prática marcados na Parte 4."),
  h2("O que é aprendizado de aplicação, não do curso"),
  p("As seções marcadas **⚑ na prática** na Parte 4 — densidade e ritmo, a proibição de escassez em perpétuo, bônus por benefício, prova sem prova social, apresentação de imagem, identidade visual e o protocolo de geração de página com IA — vêm de construir páginas reais e corrigir erros. Elas são compatíveis com o método, mas não são citação do curso."),
  p("Quando for ao ar com esses pontos, a atribuição honesta é “o que a gente aprendeu aplicando”, não “o que o curso ensina”."),
  h2("Onde estão os arquivos"),
  tabela(
    ["Material", "Onde"],
    [
      ["As 8 skills do método (o plugin)", "Repositório Comercial-Studio-Delli, pasta plugin-marketing-vtsd, branch claude/ladeira-vtsd-paid-traffic-skill-pwig1k · e no Google Drive, em 06 IA e Automação / Claude Code"],
      ["Índice das 150 aulas", "Google Drive, 05 Marketing e Conteúdo / vtsd / indice-curso.md"],
      ["Apostilas e mapas mentais", "Google Drive, 05 Marketing e Conteúdo / vtsd / materiais"],
      ["Swipe file: 30 páginas de vendas e 33 anúncios", "Google Drive, vtsd / materiais / Modulo05 / ReferenciasdeCopy"],
      ["Skills oficiais de operação do Meta Ads", "Google Drive, vtsd / skills-oficiais / trafego-com-ia-mcp"],
      ["Transcrições geradas", "Google Drive, vtsd / transcricoes"],
      ["Curso original", "Hotmart Club — Venda Todo Santo Dia, de Leandro Ladeira"],
    ],
    [3000, 6020],
  ),
  h2("Nota final"),
  p("Este dossiê é material interno de estudo e de produção de conteúdo. Ele descreve, organiza e comenta um método de trabalho; não reproduz as aulas nem redistribui os arquivos do curso. Ao usar no podcast, o crédito ao autor do método — **Leandro Ladeira, Venda Todo Santo Dia** — é o mínimo, e também é bom conteúdo: citar a fonte é uma forma de credibilidade, que é justamente um dos três elementos da persuasão."),
  esp(2),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
    border: { top: { style: BorderStyle.SINGLE, size: 6, color: H.DOURADO, space: 10 } },
    children: [new TextRun({ text: "fim do dossiê", size: 20, font: "Calibri", color: H.CINZA, italics: true })],
  }),
);

// ============================== MONTAGEM ==============================
const doc = new Document({
  creator: "Studio Delli",
  title: "Venda Todo Santo Dia — Dossiê de tráfego pago e criativos",
  description: "Método VTSD compilado como base de conteúdo para podcast",
  numbering: {
    config: [
      {
        reference: "bul",
        levels: [
          { level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 420, hanging: 260 } } } },
          { level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 840, hanging: 260 } } } },
        ],
      },
      {
        reference: "num",
        levels: [
          { level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 420, hanging: 260 } } } },
        ],
      },
    ],
  },
  styles: {
    default: {
      document: { run: { font: "Calibri", size: 22 } },
    },
  },
  sections: [
    {
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      children,
    },
  ],
});

Packer.toBuffer(doc).then((buf) => {
  require("fs").writeFileSync(process.argv[2] || "dossie.docx", buf);
  console.log("OK", buf.length, "bytes ·", children.length, "elementos");
});
